# (C) TesseractFour by ChocoParrot, 2017
# All rights reserved
# Atlas by ChocoParrot

# File ported from Dynamo on 12th October 2017
# Special thanks to Insane96MCP

gamerule doTileDrops false

execute @e[name=dyn_detIgnatius,type=armor_stand] ~ ~ ~ detect ~ 0 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:6s,RequiredPlayerRange:8s,SpawnCount:1s,MaxSpawnDelay:400s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:"Skeleton",CustomName:"Ignited Shooter",Fire:9999,ActiveEffects:[{Id:12,Amplifier:1,Duration:99999,Ambient:0b,ShowParticles:0b}],HandItems:[{id:bow,Count:1b,tag:{ench:[{id:50,lvl:1},{id:48,lvl:2}]}},{id:flint_and_steel}],HandDropChances:[-200.0f,-200.0f],DeathLootTable:"empty",ArmorItems:[{id:leather_boots,Count:1b,tag:{display:{color:0}}},{id:leather_leggings,Count:1b,tag:{display:{color:0}}},{id:leather_chestplate,Count:1b,tag:{display:{color:0}}},{id:skull,Damage:3s,Count:1b,tag:{display:{Name:"Lava Skull"},SkullOwner:{Id:"c28adcc2-f795-46e6-8862-d46ac1d7cefa",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWRmMGU4ZDQyYTZjNzFlODc4NzViOGY1OTRmZGQ0N2RkZDY3Nzg3YjUyNDE0ZTNmODE4ZDIxZGRkZWQxZDI1In19fQ=="}]}}}}],ArmorDropChances:[-200.0f,-200.0f,-200.0f,-200.0f]}}
execute @e[name=dyn_detIgnatius,type=armor_stand] ~ ~ ~ detect ~ 1 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:6s,RequiredPlayerRange:8s,SpawnCount:1s,MaxSpawnDelay:400s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:"Skeleton",CustomName:"Ignited Shooter",Fire:9999,ActiveEffects:[{Id:12,Amplifier:1,Duration:99999,Ambient:0b,ShowParticles:0b}],HandItems:[{id:bow,Count:1b,tag:{ench:[{id:50,lvl:1},{id:48,lvl:2}]}},{id:flint_and_steel}],HandDropChances:[-200.0f,-200.0f],DeathLootTable:"empty",ArmorItems:[{id:leather_boots,Count:1b,tag:{display:{color:0}}},{id:leather_leggings,Count:1b,tag:{display:{color:0}}},{id:leather_chestplate,Count:1b,tag:{display:{color:0}}},{id:skull,Damage:3s,Count:1b,tag:{display:{Name:"Lava Skull"},SkullOwner:{Id:"c28adcc2-f795-46e6-8862-d46ac1d7cefa",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWRmMGU4ZDQyYTZjNzFlODc4NzViOGY1OTRmZGQ0N2RkZDY3Nzg3YjUyNDE0ZTNmODE4ZDIxZGRkZWQxZDI1In19fQ=="}]}}}}],ArmorDropChances:[-200.0f,-200.0f,-200.0f,-200.0f]}}
execute @e[name=dyn_detIgnatius,type=armor_stand] ~ ~ ~ detect ~ 2 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:8s,RequiredPlayerRange:8s,SpawnCount:1s,MaxSpawnDelay:400s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:"zombie_pigman",CustomName:"Enraged Lavae",HandItems:[{id:stone_sword,Count:1b,tag:{ench:[{id:20,lvl:1}]}},{id:flint_and_steel,Count:1b}],HandDropChances:[-200.0f,-200.0f],Anger:400,DeathLootTable:"empty",Silent:1b,Attributes:[{Name:generic.movementSpeed,Base:0.3}],ArmorItems:[{id:leather_boots,Count:1b,tag:{display:{color:14384446}}},{id:leather_leggings,Count:1b,tag:{display:{color:14384446}}},{id:leather_chestplate,Count:1b,tag:{display:{color:14384446}}},{id:skull,Damage:3s,Count:1b,tag:{display:{Name:"Lava Creature"},SkullOwner:{Id:"e1b3e34d-03ec-4f14-be2e-5f7e4eee3ca6",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGRiZjhmNmNjZWZkOWU5Y2Y0NWNiYzIzZGI1ODFkYjI4OGM4MmRmOTQxZWYxZTNhMTZmMTgyYTY1ZTE4ZDIifX19"}]}}}}],ArmorDropChances:[-200.0f,-200.0f,-200.0f,-200.0f]}}
execute @e[name=dyn_detIgnatius,type=armor_stand] ~ ~ ~ detect ~ 3 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:6s,RequiredPlayerRange:16s,SpawnCount:1s,MaxSpawnDelay:900s,SpawnRange:10s,Delay:0s,MinSpawnDelay:600s,SpawnData:{Tags:["T4_gexempt1"],id:"Blaze",CustomName:"Igniblaze",DeathLootTable:"empty"}}
execute @e[name=dyn_detIgnatius,type=armor_stand] ~ ~ ~ detect ~ 4 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:8s,RequiredPlayerRange:8s,SpawnCount:1s,MaxSpawnDelay:400s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:"zombie_pigman",CustomName:"Enraged Lavae",HandItems:[{id:stone_sword,Count:1b,tag:{ench:[{id:20,lvl:1}]}},{id:flint_and_steel,Count:1b}],HandDropChances:[-200.0f,-200.0f],Anger:400,DeathLootTable:"empty",Silent:1b,Attributes:[{Name:generic.movementSpeed,Base:0.3}],ArmorItems:[{id:leather_boots,Count:1b,tag:{display:{color:14384446}}},{id:leather_leggings,Count:1b,tag:{display:{color:14384446}}},{id:leather_chestplate,Count:1b,tag:{display:{color:14384446}}},{id:skull,Damage:3s,Count:1b,tag:{display:{Name:"Lava Creature"},SkullOwner:{Id:"e1b3e34d-03ec-4f14-be2e-5f7e4eee3ca6",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGRiZjhmNmNjZWZkOWU5Y2Y0NWNiYzIzZGI1ODFkYjI4OGM4MmRmOTQxZWYxZTNhMTZmMTgyYTY1ZTE4ZDIifX19"}]}}}}],ArmorDropChances:[-200.0f,-200.0f,-200.0f,-200.0f]}}
kill @e[name=dyn_detIgnatius,type=armor_stand]

execute @e[name=dyn_detspawnorchard,type=armor_stand] ~ ~ ~ detect ~ 0 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:4s,RequiredPlayerRange:25s,SpawnCount:2s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:"cave_spider",CustomName:"Orchard Spider",DeathLootTable:"empty"}}
execute @e[name=dyn_detspawnorchard,type=armor_stand] ~ ~ ~ detect ~ 1 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:4s,RequiredPlayerRange:25s,SpawnCount:2s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:"cave_spider",CustomName:"Orchard Spider",DeathLootTable:"empty"}}
execute @e[name=dyn_detspawnorchard,type=armor_stand] ~ ~ ~ detect ~ 2 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:4s,RequiredPlayerRange:25s,SpawnCount:2s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:"Zombie",CustomName:"Uncanny Sunflower",ArmorItems:[{id:leather_boots,Count:1,tag:{display:{color:11642407}}},{id:leather_leggings,Count:1,tag:{display:{color:11642407}}},{id:leather_chestplate,Count:1,tag:{display:{color:11642407}}},{id:skull,Damage:3s,Count:1b,tag:{display:{Name:"Sunflower"},SkullOwner:{Id:"c3c02002-9bdd-46ec-8c08-7e3a1408f92f",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTliNzRhZWI5MGU5MTFjMWQ5MzQ2ZDcwYzYxNjRmY2ZmY2U2YjJhNDY3MWQ3MzI5ZjhjYmNmZjVjYTExOTkifX19"}]}}}}],Silent:1b,ArmorDropChances:[-50.0f,-50.0f,-50.0f,-50.0f],HandItems:[{id:stick,Count:1b},{id:double_plant,Damage:0s,Count:1b}],HandDropChances:[-200.0f,1.0f],Attributes:[{Name:zombie.spawnReinforcements,Base:0},{Name:generic.attackDamage,Base:5},{Name:generic.movementSpeed,Base:0.3}],DeathLootTable:"empty"}}
execute @e[name=dyn_detspawnorchard,type=armor_stand] ~ ~ ~ detect ~ 3 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:4s,RequiredPlayerRange:25s,SpawnCount:2s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:"Skeleton",CustomName:"Flower Wight",ArmorItems:[{},{},{id:leather_chestplate,Count:1b,tag:{display:{color:14540253}}},{id:skull,Damage:3s,Count:1b,tag:{display:{Name:"Girl Wearing a Flower Crown"},SkullOwner:{Id:"18b8f930-13df-41fe-bedf-f36cdfdf191d",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2U3YmM2MjM5MTk2ZGVkZjRmMzJlODY3NWFlMGQ5YWRhZTNhNzM1ZmIzZDdkNjg3NTg0NWI3NTAxOTc0M2VmZCJ9fX0="}]}}}}],Silent:1b,LeftHanded:1,HandItems:[{id:bow,Count:1},{id:red_flower,Damage:0s,Count:1b}],ArmorDropChances:[-50.0f,-50.0f,-50.0f,-50.0f],HandDropChances:[0.05f,1.0f],Attributes:[{Name:generic.movementSpeed,Base:0.32}],DeathLootTable:"empty",ActiveEffects:[{Id:14,Amplifier:1,Duration:999999,Ambient:1b,ShowParticles:0b}]}}
execute @e[name=dyn_detspawnorchard,type=armor_stand] ~ ~ ~ detect ~ 4 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:4s,RequiredPlayerRange:25s,SpawnCount:2s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:"Zombie",CustomName:"Uncanny Sunflower",ArmorItems:[{id:leather_boots,Count:1,tag:{display:{color:11642407}}},{id:leather_leggings,Count:1,tag:{display:{color:11642407}}},{id:leather_chestplate,Count:1,tag:{display:{color:11642407}}},{id:skull,Damage:3s,Count:1b,tag:{display:{Name:"Sunflower"},SkullOwner:{Id:"c3c02002-9bdd-46ec-8c08-7e3a1408f92f",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTliNzRhZWI5MGU5MTFjMWQ5MzQ2ZDcwYzYxNjRmY2ZmY2U2YjJhNDY3MWQ3MzI5ZjhjYmNmZjVjYTExOTkifX19"}]}}}}],Silent:1b,ArmorDropChances:[-50.0f,-50.0f,-50.0f,-50.0f],HandItems:[{id:stick,Count:1b},{id:double_plant,Damage:0s,Count:1b}],HandDropChances:[-200.0f,1.0f],Attributes:[{Name:zombie.spawnReinforcements,Base:0},{Name:generic.attackDamage,Base:5},{Name:generic.movementSpeed,Base:0.3}],DeathLootTable:"empty"}}
kill @e[name=dyn_detspawnorchard,type=armor_stand]

execute @e[name=dynchest_rmush1,type=armor_stand] ~ ~ ~ detect ~ 3 ~ bedrock -1 setblock ~ ~1 ~ chest 2 destroy {Items:[{Slot:1b,id:"minecraft:red_mushroom",Count:1b,Damage:0s},{Slot:3b,id:"minecraft:red_mushroom",Count:1b,Damage:0s},{Slot:7b,id:"minecraft:brown_mushroom",Count:1b,Damage:0s},{Slot:9b,id:"minecraft:red_mushroom",Count:1b,Damage:0s},{Slot:10b,id:"minecraft:brown_mushroom",Count:1b,Damage:0s},{Slot:13b,id:"minecraft:red_mushroom",Count:1b,Damage:0s},{Slot:14b,id:"minecraft:brown_mushroom",Count:1b,Damage:0s},{Slot:16b,id:"minecraft:brown_mushroom",Count:1b,Damage:0s},{Slot:17b,id:"minecraft:red_mushroom",Count:1b,Damage:0s},{Slot:19b,id:"minecraft:red_mushroom",Count:1b,Damage:0s},{Slot:21b,id:"minecraft:brown_mushroom",Count:1b,Damage:0s},{Slot:24b,id:"minecraft:red_mushroom",Count:1b,Damage:0s}]}
execute @e[name=dynchest_rmush1,type=armor_stand] ~ ~ ~ detect ~ 3 ~ bedrock -1 summon armor_stand ~ ~ ~ {CustomName:"PopulateChest",NoGravity:1,Invisible:1,Invulnerable:1}
execute @e[name=dynchest_rmush2,type=armor_stand] ~ ~ ~ detect ~ 3 ~ bedrock -1 setblock ~ ~1 ~ chest 2 destroy {Items:[{Slot:1b,id:"minecraft:red_mushroom",Count:1b,Damage:0s},{Slot:3b,id:"minecraft:brown_mushroom",Count:1b,Damage:0s},{Slot:6b,id:"minecraft:brown_mushroom",Count:1b,Damage:0s},{Slot:7b,id:"minecraft:red_mushroom",Count:1b,Damage:0s},{Slot:8b,id:"minecraft:brown_mushroom",Count:1b,Damage:0s},{Slot:9b,id:"minecraft:brown_mushroom",Count:1b,Damage:0s},{Slot:11b,id:"minecraft:red_mushroom",Count:1b,Damage:0s},{Slot:13b,id:"minecraft:red_mushroom",Count:1b,Damage:0s},{Slot:14b,id:"minecraft:red_mushroom",Count:1b,Damage:0s},{Slot:16b,id:"minecraft:brown_mushroom",Count:1b,Damage:0s},{Slot:18b,id:"minecraft:red_mushroom",Count:1b,Damage:0s},{Slot:21b,id:"minecraft:brown_mushroom",Count:1b,Damage:0s},{Slot:24b,id:"minecraft:brown_mushroom",Count:1b,Damage:0s},{Slot:26b,id:"minecraft:red_mushroom",Count:1b,Damage:0s}]}
execute @e[name=dynchest_rmush2,type=armor_stand] ~ ~ ~ detect ~ 3 ~ bedrock -1 summon armor_stand ~ ~ ~ {CustomName:"PopulateChest",NoGravity:1,Invisible:1,Invulnerable:1}
execute @e[name=dyn_detspawnrmush,type=armor_stand] ~ ~ ~ detect ~ 4 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:4s,RequiredPlayerRange:25s,SpawnCount:2s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],CustomName:"Mushroom Zombie",ArmorItems:[{id:leather_boots,Count:1,tag:{display:{color:9843760}}},{id:leather_leggings,Count:1,tag:{display:{color:9843760}}},{id:leather_chestplate,Count:1,tag:{display:{color:9843760}}},{id:red_mushroom_block,Count:1,damage:14s}],ArmorDropChances:[-50.0f,-50.0f,-50.0f,-50.0f],DeathLootTable:"empty",id:"Zombie"}}
kill @e[name=dyn_detspawnrmush,type=armor_stand]
kill @e[name=dynchest_rmush1,type=armor_stand]
kill @e[name=dynchest_rmush2,type=armor_stand]

execute @e[name=dyn_detmega,type=armor_stand] ~ ~ ~ detect ~ 0 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:4s,RequiredPlayerRange:10s,SpawnCount:1s,MaxSpawnDelay:800s,SpawnRange:10s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:Blaze,CustomName:"Claze",DeathLootTable:"empty"}}
execute @e[name=dyn_detmega,type=armor_stand] ~ ~ ~ detect ~ 1 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:10s,RequiredPlayerRange:10s,SpawnCount:1s,MaxSpawnDelay:200s,SpawnRange:10s,Delay:0s,MinSpawnDelay:100s,SpawnData:{Tags:["T4_gexempt1"],id:Skeleton,CustomName:"Unholy Remnant",HandItems:[{},{}],ArmorItems:[{},{},{id:"leather_chestplate",Count:1b,tag:{display:{color:14540253}}},{id:"skull",Damage:3s,Count:1b,tag:{display:{Name:"Ghost"},SkullOwner:{Id:"31152fb2-cb1e-45c3-86dd-b23f7a20a6f8",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjhkMjE4MzY0MDIxOGFiMzMwYWM1NmQyYWFiN2UyOWE5NzkwYTU0NWY2OTE2MTllMzg1NzhlYTRhNjlhZTBiNiJ9fX0="}]}}}}],ArmorDropChances:[-50.0f,-50.0f,-50.0f,-50.0f],CanPickUpLoot:0b,Silent:1b,Attributes:[{Name:generic.movementSpeed,Base:0.45},{Name:generic.maxHealth,Base:10},{Name:generic.attackDamage,Base:5}],DeathLootTable:"empty",Health:10,ActiveEffects:[{Id:14,Amplifier:1,Duration:99999,Ambient:1,ShowParticles:0}]}}
execute @e[name=dyn_detmega,type=armor_stand] ~ ~ ~ detect ~ 2 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:10s,RequiredPlayerRange:10s,SpawnCount:1s,MaxSpawnDelay:200s,SpawnRange:10s,Delay:0s,MinSpawnDelay:100s,SpawnData:{Tags:["T4_gexempt1"],id:Spider,CustomName:"Spinderoo",Attributes:[{Name:generic.movementSpeed,Base:0.4}]}}
execute @e[name=dyn_detmega,type=armor_stand] ~ ~ ~ detect ~ 3 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:10s,RequiredPlayerRange:10s,SpawnCount:1s,MaxSpawnDelay:200s,SpawnRange:10s,Delay:0s,MinSpawnDelay:100s,SpawnData:{Tags:["T4_gexempt1"],DeathLootTable:"empty",id:Skeleton,CustomName:"Haunted Guard",HandItems:[{id:bow,Count:1},{}],ArmorItems:[{},{},{id:"leather_chestplate",Count:1b,tag:{display:{color:5190175}}},{id:"skull",Damage:3s,tag:{display:{Name:""},SkullOwner:{Id:"9844e7c6-dd33-4a8f-9e9b-2a70a828da19",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzgzYmM0YTMwMzE5ZTQ2ZjE2ZGQzZWI2YTU1MzliODFjNTJlMzNiM2JiM2I1MTg0Mjc3ZWZiMjc4NmNiNyJ9fX0="}]}}}}],ActiveEffects:[{Id:14,Amplifier:1,Duration:99999,Ambient:1,ShowParticles:0}],Silent:1,Attributes:[{Name:generic.movementSpeed,Base:0.35},{Name:generic.maxHealth,Base:15}],Health:15,ArmorDropChances:[-50.0f,-50.0f,-50.0f,-50.0f]}}
execute @e[name=dyn_detmega,type=armor_stand] ~ ~ ~ detect ~ 4 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:10s,RequiredPlayerRange:10s,SpawnCount:1s,MaxSpawnDelay:800s,SpawnRange:10s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:Blaze,CustomName:"Claze",DeathLootTable:"empty"}}
kill @e[name=dyn_detmega,type=armor_stand]

execute @e[name=dyn_detspawnHive,type=armor_stand] ~ ~ ~ detect ~ 0 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:5s,RequiredPlayerRange:80s,SpawnCount:1s,MaxSpawnDelay:1000s,SpawnRange:12s,Delay:0s,MinSpawnDelay:400s,SpawnData:{Tags:["T4_gexempt1"],id:"Ghast",CustomName:"Nether Hive Ghast",DeathLootTable:"entities/creeper",ExplosionPower:1,Attributes:[{Name:generic.followRange,Base:100}],Health:6b}}
execute @e[name=dyn_detspawnHive,type=armor_stand] ~ ~ ~ detect ~ 1 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:8s,RequiredPlayerRange:80s,SpawnCount:3s,MaxSpawnDelay:1000s,SpawnRange:12s,Delay:0s,MinSpawnDelay:400s,SpawnData:{Tags:["T4_gexempt1"],id:"Blaze",DeathLootTable:"empty",Health:6b,Attributes:[{Name:generic.followRange,Base:100},{Name:generic.movementSpeed,Base:0.4}]}}
execute @e[name=dyn_detspawnHive,type=armor_stand] ~ ~ ~ detect ~ 2 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:12s,RequiredPlayerRange:16s,SpawnCount:3s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:"zombie_pigman"}}
execute @e[name=dyn_detspawnHive,type=armor_stand] ~ ~ ~ detect ~ 3 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:12s,RequiredPlayerRange:16s,SpawnCount:3s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:"zombie_pigman"}}
execute @e[name=dyn_detspawnHive,type=armor_stand] ~ ~ ~ detect ~ 4 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:5s,RequiredPlayerRange:80s,SpawnCount:1s,MaxSpawnDelay:1000s,SpawnRange:12s,Delay:0s,MinSpawnDelay:400s,SpawnData:{Tags:["T4_gexempt1"],id:"Ghast",CustomName:"Nether Hive Ghast",DeathLootTable:"entities/creeper",ExplosionPower:1,Attributes:[{Name:generic.followRange,Base:100}],Health:6b}}
kill @e[name=dyn_detspawnHive,type=armor_stand]

execute @e[name=dyn_detspawndark,type=armor_stand] ~ ~ ~ detect ~ 0 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:4s,RequiredPlayerRange:10s,SpawnCount:1s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:"wither_skeleton",CustomName:"Dark Arts Archer",HandItems:[{id:"bow",Count:1b,tag:{ench:[{id:50,lvl:1}]}},{id:"bone",Count:1}],LeftHanded:1,HandDropChances:[-200.0f,0.025f],ArmorItems:[{id:"leather_boots",Count:1,tag:{display:{color:10133921}}},{id:"leather_leggings",Count:1,tag:{display:{color:10133921}}},{id:"leather_chestplate",Count:1,tag:{display:{color:10133921}}},{id:"skull",Damage:3s,Count:1b,tag:{display:{Name:"Skull Mage"},SkullOwner:{Id:"9b24272e-9fc2-4972-8818-d5da3c3d44cf",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTZlOTM0NjdhM2EwNzkyMjdmNGE3ZDNlYmE3NjE3NTM2ZGE0OTFiYzJmYzZkNzNlZTM5NjhkM2NmMWE2YTUifX19"}]}}}}],DeathLootTable:"entities/skeleton"}}
execute @e[name=dyn_detspawndark,type=armor_stand] ~ ~ ~ detect ~ 1 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:4s,RequiredPlayerRange:10s,SpawnCount:1s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:"Spider",Passengers:[{DeathLootTable:"empty",id:"cave_spider",CustomName:"Dark Spider Jockey"}],CustomName:"Dark Spider Jockey",DeathLootTable:"empty"}}
execute @e[name=dyn_detspawndark,type=armor_stand] ~ ~ ~ detect ~ 2 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:4s,RequiredPlayerRange:10s,SpawnCount:1s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:"Zombie",CustomName:"Dark Knight",Silent:1,Health:50,Attributes:[{Name:generic.maxHealth,Base:50},{Name:generic.movementSpeed,Base:0.18},{Name:generic.attackDamage,Base:6}],HandItems:[{id:"stone_sword",Count:1b},{}],ArmorItems:[{id:"leather_boots",Count:1b,tag:{display:{color:4210752}}},{id:"leather_leggings",Count:1b,tag:{display:{color:4210752}}},{id:"leather_chestplate",Count:1b,tag:{display:{color:4210752}}},{id:"skull",Damage:3s,Count:1b,tag:{display:{Name:"Knight"},SkullOwner:{Id:"3641555a-3ae0-4f74-8f06-c475e93aae04",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTA3NDEyMTUxZTJhM2E1YjMzZjdiMjk4ZWQyMzdmYWUzOWU2NDg4ZDQ2MmZhNWQ1NThhMmViZjc0Nzg0NyJ9fX0="}]}}}}],ArmorDropChances:[-200.0f,-200.0f,-200.0f,-200.0f]}}
execute @e[name=dyn_detspawndark,type=armor_stand] ~ ~ ~ detect ~ 3 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:4s,RequiredPlayerRange:10s,SpawnCount:1s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:"zombie_pigman",Anger:400,CustomName:"Minotaur",HandItems:[{id:"golden_axe",Count:1},{}],LeftHanded:1,ArmorItems:[{id:"leather_boots",Count:1b,tag:{display:{color:5190175}}},{id:"leather_leggings",Count:1,tag:{display:{color:5190175}}},{id:"leather_chestplate",Count:1,tag:{display:{color:5190175}}},{id:"skull",Damage:3s,Count:1b,tag:{display:{Name:"The Mad Minotaur"},SkullOwner:{Id:"3b838f68-a113-40f4-b4c6-bd6500236566",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTE2ZjRkYWY1YWY2MjUzZGNkZDdlYWQ0MWJlNDRlYzc3OGRmYTAxYmRhNTdlMmVkOWVjMTEyN2UifX19"}]}}}}],ArmorDropChances:[-200.0f,-200.0f,-200.0f,-200.0f],DeathLootTable:"entities/cow",Silent:1b,Anger:100,Attributes:[{Name:generic.movementSpeed,Base:0.38},{Name:generic.attackDamage,Base:-3}]}}
execute @e[name=dyn_detspawndark,type=armor_stand] ~ ~ ~ detect ~ 4 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:4s,RequiredPlayerRange:10s,SpawnCount:1s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:"wither_skeleton",CustomName:"Dark Arts Archer",HandItems:[{id:"bow",Count:1b,tag:{ench:[{id:50,lvl:1}]}},{id:"bone",Count:1}],LeftHanded:1,HandDropChances:[-200.0f,0.025f],ArmorItems:[{id:"leather_boots",Count:1,tag:{display:{color:10133921}}},{id:"leather_leggings",Count:1,tag:{display:{color:10133921}}},{id:"leather_chestplate",Count:1,tag:{display:{color:10133921}}},{id:"skull",Damage:3s,Count:1b,tag:{display:{Name:"Skull Mage"},SkullOwner:{Id:"9b24272e-9fc2-4972-8818-d5da3c3d44cf",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTZlOTM0NjdhM2EwNzkyMjdmNGE3ZDNlYmE3NjE3NTM2ZGE0OTFiYzJmYzZkNzNlZTM5NjhkM2NmMWE2YTUifX19"}]}}}}],DeathLootTable:"entities/skeleton"}}
kill @e[name=dyn_detspawndark,type=armor_stand]

execute @e[name=dyn_detspawnD3,type=armor_stand] ~ ~ ~ detect ~ 0 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:4s,RequiredPlayerRange:8s,SpawnCount:1s,MaxSpawnDelay:400s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:"zombie_pigman",CustomName:"Overworld Pigman",HandItems:[{id:"stone_sword",Count:1b}],ArmorItems:[{id:"leather_boots",Count:1b,tag:{display:{color:3042953}}},{id:"leather_leggings",Count:1b,tag:{display:{color:3029133}}},{id:"leather_chestplate",Count:1b,tag:{display:{color:7047881}}},{id:"minecraft:skull",Damage:3s,Count:1b,tag:{display:{Name:"Frozen Pig-Zombie"},SkullOwner:{Id:"6d7b378e-d88f-4cd6-951e-9a20712ad4e0",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmM0YWExM2Q1YTFjYjM3MzAxOGZlNGE2OTJhZDdjZTY1OTg2M2IxMjlmNGFhMTNmODEwZWE2OGRkZmJiNjMifX19"}]}}}}],HandDropChances:[0.25f,0.25f],ArmorDropChances:[-200.0f,-200.0f,-200.0f,-200.0f],DeathLootTable:"entities/zombie",Anger:100}}
execute @e[name=dyn_detspawnD3,type=armor_stand] ~ ~ ~ detect ~ 1 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:4s,RequiredPlayerRange:8s,SpawnCount:1s,MaxSpawnDelay:400s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:"zombie_pigman",CustomName:"Overworld Pigman",HandItems:[{id:"stone_sword",Count:1b}],ArmorItems:[{id:"leather_boots",Count:1b,tag:{display:{color:3042953}}},{id:"leather_leggings",Count:1b,tag:{display:{color:3029133}}},{id:"leather_chestplate",Count:1b,tag:{display:{color:7047881}}},{id:"minecraft:skull",Damage:3s,Count:1b,tag:{display:{Name:"Frozen Pig-Zombie"},SkullOwner:{Id:"6d7b378e-d88f-4cd6-951e-9a20712ad4e0",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmM0YWExM2Q1YTFjYjM3MzAxOGZlNGE2OTJhZDdjZTY1OTg2M2IxMjlmNGFhMTNmODEwZWE2OGRkZmJiNjMifX19"}]}}}}],HandDropChances:[0.25f,0.25f],ArmorDropChances:[-200.0f,-200.0f,-200.0f,-200.0f],DeathLootTable:"entities/zombie",Anger:100}}
execute @e[name=dyn_detspawnD3,type=armor_stand] ~ ~ ~ detect ~ 2 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:4s,RequiredPlayerRange:8s,SpawnCount:1s,MaxSpawnDelay:400s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:"Zombie",CustomName:"Enhanced Zombie",Health:50,Attributes:[{Name:generic.maxHealth,Base:50},{Name:generic.followRange,Base:32},{Name:generic.movementSpeed,Base:0.35}],ArmorItems:[{},{},{},{id:"skull",Damage:3s,Count:1b,tag:{display:{Name:"Enhanced Zombie"},SkullOwner:{Id:"dc9ac997-cc9d-4eec-ae2c-6fc09c6f8ab1",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWYxOWY3MTc2MzNkN2RkYjhlNjQ2ZTU1YmRkYjZhYzEyNzlmNjFiYjdkMjI2NTUwNjIzM2VjZjY2MjY5In19fQ=="}]}}}}],ArmorDropChances:[-200.0f,-200.0f,-200.0f,-200.0f]}}
execute @e[name=dyn_detspawnD3,type=armor_stand] ~ ~ ~ detect ~ 3 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:1s,RequiredPlayerRange:8s,SpawnCount:1s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:600s,SpawnData:{Tags:["T4_gexempt1"],id:"Skeleton",CustomName:"Armoured Skeleton",Health:60,Attributes:[{Name:generic.maxHealth,Base:60},{Name:generic.movementSpeed,Base:0.22},{Name:generic.followRange,Base:12},{Name:generic.knockbackResistance,Base:1}],HandItems:[{id:"bow",Count:1,tag:{ench:[{id:48,lvl:2}],display:{Name:"§dFetchfeather"}}},{}],HandDropChances:[0.0025f,-200.0f],ArmorItems:[{id:"iron_boots",Count:1b},{id:"iron_leggings",Count:1b},{id:"iron_chestplate",Count:1b},{id:"skull",Damage:3s,Count:1b,tag:{display:{Name:"Endoskeleton"},SkullOwner:{Id:"77394792-e93d-42c3-8a0a-3d5de6ab4db4",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGM1MjJhZDU1ZDNkNDQzOTc1MTVmMzIzN2U2NmZhODNhNzg0YzE0Y2Y5ZWI2MjFkYmNiOGZmODFkNDQ5MzIzIn19fQ=="}]}}}}],ArmorDropChances:[0.05f,0.05f,0.05f,-200.0f]}}
execute @e[name=dyn_detspawnD3,type=armor_stand] ~ ~ ~ detect ~ 4 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:4s,RequiredPlayerRange:8s,SpawnCount:1s,MaxSpawnDelay:400s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:"Witch",CustomName:"Labywitch",DeathLootTable:"empty",Attributes:[{Name:generic.maxHealth,Base:34}],Health:34}}
kill @e[name=dyn_detspawnD3,type=armor_stand]

execute @e[name=dyn_detspawnd2,type=armor_stand] ~ ~ ~ detect ~ 0 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:4s,RequiredPlayerRange:8s,SpawnCount:1s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:"cave_spider"}}
execute @e[name=dyn_detspawnd2,type=armor_stand] ~ ~ ~ detect ~ 1 ~ bedrock -1 blockdata ~ ~ ~ {MaxNearbyEntities:4s,RequiredPlayerRange:8s,SpawnCount:1s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:"Zombie"},SpawnPotentials:[{Entity:{id:"zombie"}}]}
execute @e[name=dyn_detspawnd2,type=armor_stand] ~ ~ ~ detect ~ 2 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:4s,RequiredPlayerRange:8s,SpawnCount:1s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:"Zombie"}}
kill @e[name=dyn_detspawnd2,type=armor_stand]

execute @e[name=dyn_detspawnbirch,type=armor_stand] ~ ~ ~ detect ~ 0 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:4s,RequiredPlayerRange:25s,SpawnCount:2s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:"Witch",CustomName:"Birch Witch",DeathLootTable:"empty"}}
execute @e[name=dyn_detspawnbirch,type=armor_stand] ~ ~ ~ detect ~ 1 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:4s,RequiredPlayerRange:25s,SpawnCount:2s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:"Witch",CustomName:"Birch Witch",DeathLootTable:"empty"}}
execute @e[name=dyn_detspawnbirch,type=armor_stand] ~ ~ ~ detect ~ 2 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:4s,RequiredPlayerRange:25s,SpawnCount:2s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:"Zombie",DeathLootTable:"empty",CustomName:"Birch Warden",ArmorItems:[{id:"leather_boots",Count:1,tag:{display:{color:14540253}}},{id:"leather_leggings",Count:1,tag:{display:{color:4210752}}},{id:"leather_chestplate",Count:1,tag:{display:{color:14540253}}},{id:"minecraft:log",Damage:2s,Count:1b}],Silent:1,DeathLootTable:"empty"}}
execute @e[name=dyn_detspawnbirch,type=armor_stand] ~ ~ ~ detect ~ 3 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:4s,RequiredPlayerRange:25s,SpawnCount:2s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:"cave_spider",CustomName:"Birch Spider",DeathLootTable:"empty"}}
execute @e[name=dyn_detspawnbirch,type=armor_stand] ~ ~ ~ detect ~ 4 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:4s,RequiredPlayerRange:25s,SpawnCount:2s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:"Zombie",CustomName:"Birch Warden",DeathLootTable:"empty",ArmorItems:[{id:"leather_boots",Count:1,tag:{display:{color:14540253}}},{id:"leather_leggings",Count:1,tag:{display:{color:4210752}}},{id:"leather_chestplate",Count:1,tag:{display:{color:14540253}}},{id:"minecraft:log",Damage:2s,Count:1b}],Silent:1,DeathLootTable:"empty"}}
kill @e[name=dyn_detspawnbirch,type=armor_stand]

execute @e[name=dyn_detspawnsnf,type=armor_stand] ~ ~ ~ detect ~ 0 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:4s,RequiredPlayerRange:25s,SpawnCount:2s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],DeathLootTable:"entities/snowman",id:"Zombie",CustomName:"Baby Fort Guard",HandItems:[{id:"stone_sword",Count:1b},{}],ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{display:{color:1000000}}},{id:"minecraft:leather_leggings",Count:1b,tag:{display:{color:1000000}}},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:1000000}}},{id:"minecraft:skull",Damage:3s,tag:{display:{Name:"Snowhead"},SkullOwner:{Id:"da2407bc-43b4-4bbd-bd19-020258f61009",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjY4MTI5NjIzZmZkZTIyY2JjNTM0OTE1YWUzOGE1ZDYwZjMyZGFlZGJjNGZkNWQyYzMxMGZlYTUzN2VkIn19fQ=="}]}}}}],IsBaby:1,Silent:1,HandDropChances:[0.025f,-200.0f],ArmorDropChances:[-200.0f,-200.0f,-200.0f,-200.0f]}}
execute @e[name=dyn_detspawnsnf,type=armor_stand] ~ ~ ~ detect ~ 1 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:4s,RequiredPlayerRange:25s,SpawnCount:2s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],DeathLootTable:"entities/snowman",id:"Zombie",CustomName:"Evil Snowman",HandItems:[{id:"iron_sword",Count:1b},{}],ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{display:{color:1000000}}},{id:"minecraft:leather_leggings",Count:1b,tag:{display:{color:1000000}}},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:1000000}}},{id:"minecraft:skull",Damage:3s,tag:{display:{Name:"Evil Snowman"},SkullOwner:{Id:"f453ff13-17bf-4eb4-b92b-0d51960eabc4",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDFhMDk0ZTY4ZTZmYzM1M2ZhYWJlNDgzMTVjZjMxM2UxODZmNDMxNDJjNjE0ODI5YjlmMDM0YWI2MTM1ZTNjIn19fQ=="}]}}}}],IsBaby:0,Silent:1,HandDropChances:[0.025f,-200.0f],ArmorDropChances:[-200.0f,-200.0f,-200.0f,-200.0f]}}
execute @e[name=dyn_detspawnsnf,type=armor_stand] ~ ~ ~ detect ~ 2 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:4s,RequiredPlayerRange:25s,SpawnCount:2s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],DeathLootTable:"entities/snowman",id:"Zombie",CustomName:"Fort Guard",Attributes:[{Name:generic.maxHealth,Base:30}],Health:30,HandItems:[{id:"stone_sword",Count:1b},{}],ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{display:{color:1000000}}},{id:"minecraft:leather_leggings",Count:1b,tag:{display:{color:1000000}}},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:1000000}}},{id:"minecraft:skull",Damage:3s,tag:{display:{Name:"Snowhead"},SkullOwner:{Id:"da2407bc-43b4-4bbd-bd19-020258f61009",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjY4MTI5NjIzZmZkZTIyY2JjNTM0OTE1YWUzOGE1ZDYwZjMyZGFlZGJjNGZkNWQyYzMxMGZlYTUzN2VkIn19fQ=="}]}}}}],IsBaby:0,Silent:1,HandDropChances:[0.025f,-200.0f],ArmorDropChances:[-200.0f,-200.0f,-200.0f,-200.0f]}}
execute @e[name=dyn_detspawnsnf,type=armor_stand] ~ ~ ~ detect ~ 3 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:4s,RequiredPlayerRange:25s,SpawnCount:2s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],DeathLootTable:"entities/polar_bear",id:"Skeleton",CustomName:"Polar Bear",Attributes:[{Name:generic.maxHealth,Base:30},{Name:generic.attackDamage,Base:5}],Health:30,HandItems:[{},{}],ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{display:{color:14540253}}},{id:"minecraft:leather_leggings",Count:1b,tag:{display:{color:14540253}}},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:14540253 }}},{id:"minecraft:skull",Damage:3s,tag:{display:{Name:"Polar Bear"},SkullOwner:{Id:"87324464-1700-468f-8333-e7779ec8c21e",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDQ2ZDIzZjA0ODQ2MzY5ZmEyYTM3MDJjMTBmNzU5MTAxYWY3YmZlODQxOTk2NjQyOTUzM2NkODFhMTFkMmIifX19"}]}}}}],Silent:1,HandDropChances:[0.025f,-200.0f],ArmorDropChances:[-200.0f,-200.0f,-200.0f,-200.0f]}}
execute @e[name=dyn_detspawnsnf,type=armor_stand] ~ ~ ~ detect ~ 4 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:4s,RequiredPlayerRange:25s,SpawnCount:2s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],DeathLootTable:"entities/snowman",id:"Zombie",CustomName:"Evil Snowman",HandItems:[{id:"iron_sword",Count:1b},{}],ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{display:{color:1000000}}},{id:"minecraft:leather_leggings",Count:1b,tag:{display:{color:1000000}}},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:1000000}}},{id:"minecraft:skull",Damage:3s,tag:{display:{Name:"Evil Snowman"},SkullOwner:{Id:"f453ff13-17bf-4eb4-b92b-0d51960eabc4",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDFhMDk0ZTY4ZTZmYzM1M2ZhYWJlNDgzMTVjZjMxM2UxODZmNDMxNDJjNjE0ODI5YjlmMDM0YWI2MTM1ZTNjIn19fQ=="}]}}}}],IsBaby:0,Silent:1,HandDropChances:[0.025f,-200.0f],ArmorDropChances:[-200.0f,-200.0f,-200.0f,-200.0f]}}
kill @e[name=dyn_detspawnsnf,type=armor_stand]

execute @e[name=dyn_detspawnit,type=armor_stand] ~ ~ ~ detect ~ 0 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:12s,RequiredPlayerRange:32s,SpawnCount:3s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:"Blaze",CustomName:"Ice Blaze",HandItems:[{id:"packed_ice",Count:1b},{}],ArmorItems:[{id:"packed_ice",Count:1b},{id:"packed_ice",Count:1b},{id:"packed_ice",Count:1b},{id:"packed_ice",Count:1b}],HandDropChances:[0.5f,-200.0f],ArmorDropChances:[0.5f,0.5f,0.5f,0.5f],DeathLootTable:"entities/snowman"}}
execute @e[name=dyn_detspawnit,type=armor_stand] ~ ~ ~ detect ~ 1 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:12s,RequiredPlayerRange:32s,SpawnCount:3s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:"Zombie",CustomName:"Ice Tower Rogue",DeathLootTable:"empty",Attributes:[{Name:generic.movementSpeed,Base:0.35}],HandItems:[{id:"minecraft:stone_sword",Count:1b},{}],ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{display:{color:3029133}}},{id:"minecraft:leather_leggings",Count:1b,tag:{display:{color:7047881}}},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:3029133}}},{id:"minecraft:snow",Damage:0s,Count:1b}],HandDropChances:[0.05f,-200.0f],ArmorDropChances:[0.05f,0.05f,0.05f,0.00f],Silent:1b}}
execute @e[name=dyn_detspawnit,type=armor_stand] ~ ~ ~ detect ~ 2 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:12s,RequiredPlayerRange:32s,SpawnCount:3s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:"Skeleton",CustomName:"Ice Archer",DeathLootTable:"entities/snowman",Attributes:[{Name:generic.movementSpeed,Base:0.35}],HandItems:[{id:"minecraft:bow",Count:1b},{}],ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{display:{color:3029133}}},{id:"minecraft:leather_leggings",Count:1b,tag:{display:{color:7047881}}},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:3029133}}},{id:"minecraft:skull",Damage:3s,Count:1b,tag:{display:{Name:"Snowman with a blue hat"},SkullOwner:{Id:"a94ef687-5b4a-4d77-9f3b-428c765b8c37",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzRhMWQ4ZDNjNzZmMTA3OTM1MTcxMTQ2ZTU1ZTA3ZGZmNWI1ODcxNTU0N2I2ZTVkZWZmNmE1YzIwZDViZTQwIn19fQ=="}]}}}}],HandDropChances:[0.05f,0.0],ArmorDropChances:[0.05f,0.05f,0.05f,0.00f],Silent:1b}}
execute @e[name=dyn_detspawnit,type=armor_stand] ~ ~ ~ detect ~ 3 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:12s,RequiredPlayerRange:32s,SpawnCount:3s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:"Skeleton",CustomName:"Snow Warrior",HandItems:[{id:"minecraft:iron_sword",Count:1b},{}],ArmorItems:[{id:"minecraft:iron_boots",Count:1b},{},{id:"minecraft:iron_chestplate"},{id:"minecraft:ice",Count:1b}],HandDropChances:[0.025f,-200.0f],ArmorDropChances:[0.025f,0.025f,0.025f,0.00f],ActiveEffects:[{Id:14,Amplifier:1,Duration:9999999,Ambient:2}],DeathLootTable:"empty"}}
execute @e[name=dyn_detspawnit,type=armor_stand] ~ ~ ~ detect ~ 4 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:12s,RequiredPlayerRange:32s,SpawnCount:3s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s,SpawnData:{Tags:["T4_gexempt1"],id:"Blaze",CustomName:"Ice Blaze",HandItems:[{id:"packed_ice",Count:1b},{}],ArmorItems:[{id:"packed_ice",Count:1b},{id:"packed_ice",Count:1b},{id:"packed_ice",Count:1b},{id:"packed_ice",Count:1b}],HandDropChances:[0.5f,-200.0f],ArmorDropChances:[0.5f,0.5f,0.5f,0.5f],DeathLootTable:"entities/snowman"}}
kill @e[name=dyn_detspawnit,type=armor_stand]

execute @e[name=dyn_detspawndungeon,type=armor_stand] ~ ~ ~ detect ~ 0 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {SpawnData:{Tags:["T4_gexempt1"],id:"Spider"},MaxNearbyEntities:8s,RequiredPlayerRange:25s,SpawnCount:2s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s}
execute @e[name=dyn_detspawndungeon,type=armor_stand] ~ ~ ~ detect ~ 1 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {SpawnData:{Tags:["T4_gexempt1"],id:"Creeper"},MaxNearbyEntities:8s,RequiredPlayerRange:25s,SpawnCount:2s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s}
execute @e[name=dyn_detspawndungeon,type=armor_stand] ~ ~ ~ detect ~ 2 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {SpawnData:{Tags:["T4_gexempt1"],id:"Zombie"},MaxNearbyEntities:8s,RequiredPlayerRange:25s,SpawnCount:2s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s}
execute @e[name=dyn_detspawndungeon,type=armor_stand] ~ ~ ~ detect ~ 3 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {SpawnData:{Tags:["T4_gexempt1"],id:"Skeleton"},MaxNearbyEntities:8s,RequiredPlayerRange:25s,SpawnCount:2s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s}
execute @e[name=dyn_detspawndungeon,type=armor_stand] ~ ~ ~ detect ~ 4 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {SpawnData:{Tags:["T4_gexempt1"],id:"Spider"},MaxNearbyEntities:8s,RequiredPlayerRange:25s,SpawnCount:2s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s}
kill @e[name=dyn_detspawndungeon,type=armor_stand]

execute @e[name=plive_dandelionUndergroundsSpawn,type=armor_stand] ~ ~ ~ detect ~ 0 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {SpawnData:{Tags:["T4_gexempt1"],id:"cave_spider",DeathLootTable:"empty"},MaxNearbyEntities:6s,RequiredPlayerRange:18s,SpawnCount:2s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s}
execute @e[name=plive_dandelionUndergroundsSpawn,type=armor_stand] ~ ~ ~ detect ~ 1 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {SpawnData:{Tags:["T4_gexempt1"],id:"wither_skeleton",DeathLootTable:"empty",HandItems:[{id:"minecraft:stone_sword",Count:1b},{}]},MaxNearbyEntities:6s,RequiredPlayerRange:18s,SpawnCount:2s,MaxSpawnDelay:800s,SpawnRange:10s,Delay:0s,MinSpawnDelay:200s}
execute @e[name=plive_dandelionUndergroundsSpawn,type=armor_stand] ~ ~ ~ detect ~ 2 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {SpawnData:{Tags:["T4_gexempt1"],id:"Zombie",DeathLootTable:"empty"},MaxNearbyEntities:6s,RequiredPlayerRange:18s,SpawnCount:2s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s}
execute @e[name=plive_dandelionUndergroundsSpawn,type=armor_stand] ~ ~ ~ detect ~ 3 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {SpawnData:{Tags:["T4_gexempt1"],id:"Skeleton",DeathLootTable:"empty",HandItems:[{id:"minecraft:wooden_sword",Count:1b},{}],MaxNearbyEntities:6s,RequiredPlayerRange:18s,SpawnCount:2s,MaxSpawnDelay:800s,SpawnRange:10s,Delay:0s,MinSpawnDelay:200s}
execute @e[name=plive_dandelionUndergroundsSpawn,type=armor_stand] ~ ~ ~ detect ~ 4 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {SpawnData:{Tags:["T4_gexempt1"],id:"cave_spider",DeathLootTable:"empty"},MaxNearbyEntities:6s,RequiredPlayerRange:18s,SpawnCount:2s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s}
kill @e[name=plive_dandelionUndergroundsSpawn,type=armor_stand]

execute @e[name=dyn_detspawnjcrypt,type=armor_stand] ~ ~ ~ detect ~ 0 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {SpawnData:{Tags:["T4_gexempt1"],id:"Zombie",CustomName:"Defeated Explorer",HandItems:[{id:wooden_sword,Count:1b},{id:wooden_pickaxe,Count:1b}],HandDropChances:[0.25,0.25],ArmorItems:[{id:leather_boots,Count:1b},{id:leather_leggings,Count:1b},{id:leather_chestplate,Count:1b},{id:skull,Damage:3s,Count:1b,tag:{display:{Name:"Dead Explorer"},SkullOwner:{Id:"6f45ccba-f11e-4d0e-a852-48999cf481a4",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmU4YzVmMzU1ZDFjM2UxMWUyMjlkNjViZDMzZGY4ZTBjZTVhYjY0NDRhODFhODU0NTJjNjFjMWNmYjJkZDllIn19fQ=="}]}}}}],Silent:1b,Attributes:[{Name:generic.followRange,Base:20},{Name:generic.movementSpeed,Base:0.4},{Name:generic.maxHealth,Base:30},{Name:generic.attackDamage,Base:2}],Health:20,ActiveEffects:[{Id:14,Amplifier:1,Duration:99999,Ambient:1b,ShowParticles:0b}],DeathLootTable:"empty",ArmorDropChances:[-50.0f,-50.0f,-50.0f,-50.0f]},MaxNearbyEntities:6s,RequiredPlayerRange:16s,SpawnCount:2s,MaxSpawnDelay:1200,SpawnRange:12s,Delay:0s,MinSpawnDelay:1000s}
execute @e[name=dyn_detspawnjcrypt,type=armor_stand] ~ ~ ~ detect ~ 1 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {SpawnData:{Tags:["T4_gexempt1"],id:"minecraft:snowball",Passengers:[{id:"husk",CustomName:"Crypt Husk",Attributes:[{Name:generic.movementSpeed,Base:0.45},{Name:generic.followRange,Base:30}],DeathLootTable:"empty"}]},SpawnCount:4,SpawnRange:4,RequiredPlayerRange:20,Delay:60,MinSpawnDelay:800,MaxSpawnDelay:200,MaxNearbyEntities:8}
execute @e[name=dyn_detspawnjcrypt,type=armor_stand] ~ ~ ~ detect ~ 2 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {SpawnData:{Tags:["T4_gexempt1"],id:"Spider",CustomName:"Crypterspider",DeathLootTable:"empty"},MaxNearbyEntities:20s,RequiredPlayerRange:16s,SpawnCount:2s,MaxSpawnDelay:800s,SpawnRange:12s,Delay:0s,MinSpawnDelay:200s}
execute @e[name=dyn_detspawnjcrypt,type=armor_stand] ~ ~ ~ detect ~ 3 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {SpawnData:{Tags:["T4_gexempt1"],id:"Skeleton",CustomName:"Crypt Guardian",HandItems:[{id:bow,Count:1b,tag:{ench:[{id:48,lvl:1},{id:49,lvl:1}]}},{id:rotten_flesh,Count:1b}],HandDropChances:[-200.0f,0.025f],ArmorItems:[{id:leather_boots,Count:1b,tag:{display:{color:5190175}}},{id:leather_leggings,Count:1b,tag:{display:{color:5190175}}},{id:leather_chestplate,Count:1b,tag:{display:{color:5190175}}},{id:skull,Damage:3s,Count:1b,tag:{display:{Name:"Crypt Guardian"},SkullOwner:{Id:"d4576dca-a99e-4875-a319-81b4e61c0579",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTczM2Q1YTMzMGJiYmQ0MGUzYjZhNWRmYWY4MGFmNTMzZGYxZmFmOTE1ZDg4Y2I4OTEyNDg5YWI3ZDA2YWIwIn19fQ=="}]}}}}],DeathLootTable:"entities/zombie",CustomName:"Crypt Guardian",ArmorDropChances:[-50.0f,-50.0f,-50.0f,-50.0f],Health:25,Attributes:[{Name:generic.maxHealth,Base:25}],Silent:1b},MaxNearbyEntities:8s,RequiredPlayerRange:16s,SpawnCount:2s,MaxSpawnDelay:800s,SpawnRange:8s,Delay:0s,MinSpawnDelay:200s}
execute @e[name=dyn_detspawnjcrypt,type=armor_stand] ~ ~ ~ detect ~ 4 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {SpawnData:{Tags:["T4_gexempt1"],id:"Zombie",CustomName:"Defeated Explorer",HandItems:[{id:wooden_sword,Count:1b},{id:wooden_pickaxe,Count:1b}],HandDropChances:[0.25,0.25],ArmorItems:[{id:leather_boots,Count:1b},{id:leather_leggings,Count:1b},{id:leather_chestplate,Count:1b},{id:skull,Damage:3s,Count:1b,tag:{display:{Name:"Dead Explorer"},SkullOwner:{Id:"6f45ccba-f11e-4d0e-a852-48999cf481a4",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmU4YzVmMzU1ZDFjM2UxMWUyMjlkNjViZDMzZGY4ZTBjZTVhYjY0NDRhODFhODU0NTJjNjFjMWNmYjJkZDllIn19fQ=="}]}}}}],Silent:1b,Attributes:[{Name:generic.followRange,Base:20},{Name:generic.movementSpeed,Base:0.4},{Name:generic.maxHealth,Base:30},{Name:generic.attackDamage,Base:2}],Health:20,ActiveEffects:[{Id:14,Amplifier:1,Duration:99999,Ambient:1b,ShowParticles:0b}],DeathLootTable:"empty",ArmorDropChances:[-50.0f,-50.0f,-50.0f,-50.0f]},MaxNearbyEntities:6s,RequiredPlayerRange:16s,SpawnCount:2s,MaxSpawnDelay:1800,SpawnRange:8s,Delay:0s,MinSpawnDelay:1000s}
kill @e[name=dyn_detspawnjcrypt,type=armor_stand]

execute @e[name=dyn_detspawnsdungeon,type=armor_stand] ~ ~ ~ detect ~ 0 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {SpawnData:{Tags:["T4_gexempt1"],id:"husk",CustomName:"Sandy Husk",ArmorItems:[{id:leather_boots,Count:1b,tag:{display:{color:15196837}}},{id:leather_leggings,Count:1b,tag:{display:{color:15196837}}},{id:leather_chestplate,Count:1b,tag:{display:{color:15196837}}},{id:sand,Count:1b}],ArmorDropChances:[-200.0f,-200.0f,-200.0f,0.5f],DeathLootTable:"empty"},MaxNearbyEntities:8s,RequiredPlayerRange:16s,SpawnCount:2s,MaxSpawnDelay:800,SpawnRange:12s,Delay:0s,MinSpawnDelay:200s}
execute @e[name=dyn_detspawnsdungeon,type=armor_stand] ~ ~ ~ detect ~ 2 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {SpawnData:{Tags:["T4_gexempt1"],id:"Skeleton",CustomName:"Sandy Skeleton",HandItems:[{id:bow,Count:1b},{id:deadbush,Count:1b}],ArmorItems:[{id:leather_boots,Count:1b,tag:{display:{color:15196837}}},{id:leather_leggings,Count:1b,tag:{display:{color:15196837}}},{id:leather_chestplate,Count:1b,tag:{display:{color:15196837}}},{id:sand,Count:2b}],ArmorDropChances:[-200.0f,-200.0f,-200.0f,0.1f],DeathLootTable:"empty"},MaxNearbyEntities:8s,RequiredPlayerRange:16s,SpawnCount:2s,MaxSpawnDelay:800s,SpawnRange:12s,Delay:0s,MinSpawnDelay:200s}
kill @e[name=dyn_detspawnsdungeon,type=armor_stand]

execute @e[name=dyn_detspawnredd,type=armor_stand] ~ ~ ~ detect ~ 0 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {SpawnData:{Tags:["T4_gexempt1"],id:"cave_spider",CustomName:"Mesa Spider",DeathLootTable:"empty"},MaxNearbyEntities:8s,RequiredPlayerRange:16s,SpawnCount:2s,MaxSpawnDelay:800,SpawnRange:12s,Delay:0s,MinSpawnDelay:200s}
execute @e[name=dyn_detspawnredd,type=armor_stand] ~ ~ ~ detect ~ 2 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {SpawnData:{Tags:["T4_gexempt1"],id:"husk",CustomName:"Mesa Husk",ArmorItems:[{id:leather_boots,Count:1b,tag:{display:{color:15636517}}},{id:leather_leggings,Count:1b,tag:{display:{color:15636517}}},{id:leather_chestplate,Count:1b,tag:{display:{color:15636517}}},{id:sand,Damage:1s,Count:1b}],ArmorDropChances:[-200.0f,-200.0f,-200.0f,0.5f],DeathLootTable:"empty"},MaxNearbyEntities:8s,RequiredPlayerRange:16s,SpawnCount:2s,MaxSpawnDelay:800s,SpawnRange:12s,Delay:0s,MinSpawnDelay:200s}
execute @e[name=dyn_detspawnredd,type=armor_stand] ~ ~ ~ detect ~ 0 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {SpawnData:{Tags:["T4_gexempt1"],id:"Zombie",CustomName:"Sandshrew",HandItems:[{},{}],ArmorItems:[{id:leather_boots,Count:1b,tag:{display:{color:15636517}}},{id:leather_leggings,Count:1b,tag:{display:{color:15636517}}},{id:leather_chestplate,Count:1b,tag:{display:{color:15636517}}},{id:skull,Damage:3s,Count:1b,tag:{display:{Name:"Sandshrew"},SkullOwner:{Id:"3cacbc40-f7aa-492d-b98c-a27ec5e352be",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTBhNzliNjhhOTI4OGM2YWQwYmFiZTRlMWEyZWFmMTU2NjNkMjMzNmJmNWQyY2FkMmVkYmE5YmNhNzE0ODhlIn19fQ=="}]}}}}],ArmorDropChances:[-50.0f,-50.0f,-50.0f,-50.0f],DeathLootTable:"empty",Silent:1b},MaxNearbyEntities:8s,RequiredPlayerRange:16s,SpawnCount:2s,MaxSpawnDelay:800,SpawnRange:12s,Delay:0s,MinSpawnDelay:200s}
kill @e[name=dyn_detspawnredd,type=armor_stand]

execute @e[name=dyn_detspawnpharaoh,type=armor_stand] ~ ~ ~ detect ~ 0 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:4s,RequiredPlayerRange:10s,SpawnCount:1s,MaxSpawnDelay:800s,SpawnRange:10s,Delay:0s,MinSpawnDelay:400s,SpawnData:{Tags:["T4_gexempt1"],id:"Blaze",DeathLootTable:"empty",CustomName:"Pharaoh's Blaze"}}
execute @e[name=dyn_detspawnpharaoh,type=armor_stand] ~ ~ ~ detect ~ 1 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:10s,RequiredPlayerRange:10s,SpawnCount:1s,MaxSpawnDelay:400s,SpawnRange:10s,Delay:0s,MinSpawnDelay:300s,SpawnData:{Tags:["T4_gexempt1"],id:"Zombie",CustomName:"Haunting Apparition",ArmorItems:[{id:leather_boots,Count:1b,tag:{display:{color:4663815}}},{id:leather_leggings,Count:1b,tag:{display:{color:4663815}}},{id:leather_chestplate,Count:1b,tag:{display:{color:4663815}}},{id:skull,Damage:3s,Count:1b,tag:{display:{Name:"Apparition"},SkullOwner:{Id:"3ee188a6-2c6a-4c26-98a5-d655d4eed50f",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTE3MWJhYTVhZDE2N2JkMzNlNDE5ZmU3NDVmN2IwMTg0MGNiNmQ3ZThkN2FlYzZjZGEzMWNlMmQ1Y2Y2MSJ9fX0="}]}}}}],ArmorDropChances:[-50.0f,-50.0f,-50.0f,-50.0f],Health:15s,DeathLootTable:"empty",Silent:1b,ActiveEffects:[{Id:14,Amplifier:1,Duration:999999,ShowParticles:0b,Ambient:1b}],Attributes:[{Name:generic.movementSpeed,Base:0.3},{Name:generic.attackDamage,Base:6},{Name:generic.maxHealth,Base:13}]}}
execute @e[name=dyn_detspawnpharaoh,type=armor_stand] ~ ~ ~ detect ~ 2 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:4s,RequiredPlayerRange:10s,SpawnCount:1s,MaxSpawnDelay:800s,SpawnRange:10s,Delay:0s,MinSpawnDelay:400s,SpawnData:{Tags:["T4_gexempt1"],id:"Blaze",DeathLootTable:"empty",CustomName:"Pharaoh's Blaze"}}
execute @e[name=dyn_detspawnpharaoh,type=armor_stand] ~ ~ ~ detect ~ 3 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:10s,RequiredPlayerRange:10s,SpawnCount:1s,MaxSpawnDelay:200s,SpawnRange:10s,Delay:0s,MinSpawnDelay:100s,SpawnData:{Tags:["T4_gexempt1"],id:"Skeleton",CustomName:"Seeker Archer",ArmorItems:[{id:leather_boots,Count:1b,tag:{display:{color:14932354}}},{id:leather_leggings,Count:1b,tag:{display:{color:14932354}}},{id:leather_chestplate,Count:1b,tag:{display:{color:14932354}}},{id:skull,Damage:3s,Count:1b,tag:{display:{Name:"Seeker"},SkullOwner:{Id:"f384ad23-42b7-4a4f-838f-0f903f531e2c",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmFjN2ZmNjY1Y2FlMmI2MjY4ZDc3YTQ1ZDRiMjI3ODk5ZTY4N2RhYmFkZWQ3OTZmNTZhNTIxNmM0YmEzMWE3In19fQ=="}]}}}}],ArmorDropChances:[-50.0f,-50.0f,-50.0f,-50.0f],HandItems:[{id:bow,Count:1b,tag:{ench:[{id:48,lvl:2}]}},{id:wooden_hoe,Count:1b}],HandDropChances:[-200.0f,-200.0f],DeathLootTable:"empty",Silent:1b,Health:15s,Attributes:[{Name:generic.maxHealth,Base:13}]}}
execute @e[name=dyn_detspawnpharaoh,type=armor_stand] ~ ~ ~ detect ~ 4 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {MaxNearbyEntities:10s,RequiredPlayerRange:10s,SpawnCount:4s,MaxSpawnDelay:200s,SpawnRange:10s,Delay:0s,MinSpawnDelay:100s,SpawnData:{Tags:["T4_gexempt1"],id:"Silverfish",CustomName:"Tomb Pest",DeathLootTable:"empty",Attributes:[{Name:generic.followRange,Base:30},{Name:generic.movementSpeed,Base:0.3}]}}
kill @e[name=dyn_detspawnpharaoh,type=armor_stand]

execute @e[name=dyn_detspawnscavern,type=armor_stand] ~ ~ ~ detect ~ 0 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {SpawnData:{Tags:["T4_gexempt1"],id:"Zombie",CustomName:"Soul Monster",ArmorItems:[{id:leather_boots,Count:1b,tag:{display:{color:3282436}}},{id:leather_leggings,Count:1b,tag:{display:{color:3282436}}},{id:leather_chestplate,Count:1b,tag:{display:{color:3282436}}},{id:skull,Damage:3s,Count:1b,tag:{display:{Name:"Soul Monster"},SkullOwner:{Id:"a452f70e-85e3-4cf8-b02d-f674d1c81628",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTg3MDk1ZmFmMzMxNzgzMTJmNjEyOGI5Y2Q0YWZjNTIzMGRiNjA5Y2I2Mzk2M2ZmYmRlYmVmOTQ4MTdiMzM3MyJ9fX0="}]}}}}],ArmorDropChances:[-50.0f,-50.0f,-50.0f,-50.0f],Silent:1b,DeathLootTable:"empty"},MaxNearbyEntities:8s,RequiredPlayerRange:16s,SpawnCount:2s,MaxSpawnDelay:800,SpawnRange:12s,Delay:0s,MinSpawnDelay:200s}
execute @e[name=dyn_detspawnscavern,type=armor_stand] ~ ~ ~ detect ~ 2 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {SpawnData:{Tags:["T4_gexempt1"],id:"wither_skeleton",HandItems:[{id:bow,Count:1b},{}],CustomName:"Soul Archer",ArmorItems:[{id:leather_boots,Count:1b,tag:{display:{color:3282436}}},{id:leather_leggings,Count:1b,tag:{display:{color:3282436}}},{id:leather_chestplate,Count:1b,tag:{display:{color:3282436}}},{id:skull,Damage:3s,Count:1b,tag:{display:{Name:"Soul Monster"},SkullOwner:{Id:"a452f70e-85e3-4cf8-b02d-f674d1c81628",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTg3MDk1ZmFmMzMxNzgzMTJmNjEyOGI5Y2Q0YWZjNTIzMGRiNjA5Y2I2Mzk2M2ZmYmRlYmVmOTQ4MTdiMzM3MyJ9fX0="}]}}}}],ArmorDropChances:[-50.0f,-50.0f,-50.0f,-50.0f],Silent:1b,DeathLootTable:"empty"},MaxNearbyEntities:8s,RequiredPlayerRange:16s,SpawnCount:2s,MaxSpawnDelay:800s,SpawnRange:12s,Delay:0s,MinSpawnDelay:200s}
kill @e[name=dyn_detspawnscavern,type=armor_stand]

execute @e[name=dyn_detspawnmcastle,type=armor_stand] ~ ~ ~ detect ~ 0 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {SpawnData:{Tags:["T4_gexempt1"],id:"Zombie",DeathLootTable:"none"},MaxNearbyEntities:4s,RequiredPlayerRange:8s,SpawnCount:2s,MaxSpawnDelay:800,SpawnRange:12s,Delay:0s,MinSpawnDelay:200s}
execute @e[name=dyn_detspawnmcastle,type=armor_stand] ~ ~ ~ detect ~ 2 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {SpawnData:{Tags:["T4_gexempt1"],id:"Skeleton",DeathLootTable:"none"},MaxNearbyEntities:4s,RequiredPlayerRange:8s,SpawnCount:2s,MaxSpawnDelay:800s,SpawnRange:12s,Delay:0s,MinSpawnDelay:200s}
kill @e[name=dyn_detspawnscavern,type=armor_stand]

execute @e[name=dyn_detspawnnfortif,type=armor_stand] ~ ~ ~ detect ~ 0 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {SpawnData:{Tags:["T4_gexempt1"],id:"Zombie",CustomName:"Hell-guard",ArmorItems:[{id:leather_boots,Count:1b,tag:{display:{color:13311488}}},{id:leather_leggings,Count:1b,tag:{display:{color:13311488}}},{id:leather_chestplate,Count:1b,tag:{display:{color:13311488}}},{id:skull,Damage:3s,Count:1b,tag:{display:{Name:"Hell-guard"},SkullOwner:{Id:"bb3a205e-9a69-4994-8f1a-a27d30cafb8e",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmQyN2YxMzBjMWFjZGQ3ODRjZWVlMmI3NWZiMTgxZmE1MmZmM2E3NTAyNDU3NGViNGFmN2ZhZjFhZTc1YmMifX19"}]}}}}],DeathLootTable:"empty",Attributes:[{Name:generic.maxHealth,Base:13},{Name:generic.movementSpeed,Base:0.3}],Health:13,ArmorDropChances:[-200.0f,-200.0f,-200.0f,-200.0f],Silent:1b,Fire:30000,ActiveEffects:[{Id:12,Amplifier:1,Duration:99999,ShowParticles:0b,Ambient:1b},{Id:14,Amplifier:1,Duration:999999,Ambient:1b,ShowParticles:0b}]},MaxNearbyEntities:4s,RequiredPlayerRange:8s,SpawnCount:2s,MaxSpawnDelay:800,SpawnRange:12s,Delay:0s,MinSpawnDelay:200s}
execute @e[name=dyn_detspawnnfortif,type=armor_stand] ~ ~ ~ detect ~ 2 ~ bedrock -1 setblock ~ ~ ~ mob_spawner 0 destroy {SpawnData:{Tags:["T4_gexempt1"],id:"cave_spider",CustomName:"Fortified Spider",Attributes:[{Name:generic.movementSpeed,Base:0.3},{Name:generic.attackDamage,Base:3}],ActiveEffects:[{Id:12,Amplifier:1,Duration:999999,Ambient:1b,ShowParticles:0b}],DeathLootTable:"empty"},MaxNearbyEntities:4s,RequiredPlayerRange:8s,SpawnCount:2s,MaxSpawnDelay:800s,SpawnRange:12s,Delay:0s,MinSpawnDelay:200s}
kill @e[name=dyn_detspawnnfortif,type=armor_stand]

gamerule doTileDrops true
