# (C) TesseractFour by ChocoParrot, 2017
# All rights reserved
# Equines by ChocoParrot

# General equines devaluation - feet slot
# Speed - mainhand slot
# Jump & health - leggings

# Entitydata
entitydata @s[score_T4_Eq_jump_min=1,score_T4_Eq_jump=1] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.010910416d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.014583333d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=2,score_T4_Eq_jump=2] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.021820832d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.029166666d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=3,score_T4_Eq_jump=3] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.032731248d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.043749999d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=4,score_T4_Eq_jump=4] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.043641664d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.058333332d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=5,score_T4_Eq_jump=5] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.054552079999999996d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.072916665d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=6,score_T4_Eq_jump=6] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.065462496d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.087499998d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=7,score_T4_Eq_jump=7] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.07637291199999999d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.102083331d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=8,score_T4_Eq_jump=8] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.087283328d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.116666664d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=9,score_T4_Eq_jump=9] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.098193744d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.131249997d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=10,score_T4_Eq_jump=10] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.10910415999999999d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.14583333d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=11,score_T4_Eq_jump=11] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.12001457599999998d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.16041666300000001d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=12,score_T4_Eq_jump=12] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.130924992d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.174999996d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=13,score_T4_Eq_jump=13] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.141835408d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.189583329d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=14,score_T4_Eq_jump=14] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.15274582399999997d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.204166662d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=15,score_T4_Eq_jump=15] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.16365623999999998d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.218749995d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=16,score_T4_Eq_jump=16] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.174566656d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.233333328d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=17,score_T4_Eq_jump=17] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.185477072d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.247916661d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=18,score_T4_Eq_jump=18] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.196387488d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.262499994d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=19,score_T4_Eq_jump=19] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.20729790399999998d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.277083327d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=20,score_T4_Eq_jump=20] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.21820831999999998d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.29166666d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=21,score_T4_Eq_jump=21] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.229118736d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.306249993d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=22,score_T4_Eq_jump=22] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.24002915199999997d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.32083332600000003d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=23,score_T4_Eq_jump=23] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.250939568d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.335416659d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=24,score_T4_Eq_jump=24] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.261849984d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.349999992d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=25,score_T4_Eq_jump=25] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.27276039999999996d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.364583325d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=26,score_T4_Eq_jump=26] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.283670816d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.379166658d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=27,score_T4_Eq_jump=27] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.29458123199999997d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.393749991d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=28,score_T4_Eq_jump=28] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.30549164799999995d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.408333324d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=29,score_T4_Eq_jump=29] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.316402064d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.42291665700000003d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=30,score_T4_Eq_jump=30] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.32731247999999996d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.43749999d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=31,score_T4_Eq_jump=31] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.338222896d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.45208332300000004d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=32,score_T4_Eq_jump=32] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.349133312d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.466666656d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=33,score_T4_Eq_jump=33] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.36004372799999995d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.481249989d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=34,score_T4_Eq_jump=34] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.370954144d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.495833322d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=35,score_T4_Eq_jump=35] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.38186455999999996d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.510416655d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=36,score_T4_Eq_jump=36] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.392774976d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.524999988d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=37,score_T4_Eq_jump=37] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.403685392d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.5395833210000001d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=38,score_T4_Eq_jump=38] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.41459580799999995d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.554166654d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=39,score_T4_Eq_jump=39] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.425506224d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.568749987d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=40,score_T4_Eq_jump=40] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.43641663999999997d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.58333332d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=41,score_T4_Eq_jump=41] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.44732705599999995d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.597916653d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=42,score_T4_Eq_jump=42] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.458237472d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.612499986d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=43,score_T4_Eq_jump=43] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.46914788799999996d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.627083319d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=44,score_T4_Eq_jump=44] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.48005830399999994d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.6416666520000001d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=45,score_T4_Eq_jump=45] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.49096871999999997d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.656249985d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=46,score_T4_Eq_jump=46] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.501879136d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.670833318d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=47,score_T4_Eq_jump=47] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.512789552d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.685416651d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=48,score_T4_Eq_jump=48] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.523699968d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.699999984d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=49,score_T4_Eq_jump=49] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.5346103839999999d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.714583317d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=50,score_T4_Eq_jump=50] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.5455207999999999d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.72916665d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=51,score_T4_Eq_jump=51] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.556431216d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.7437499830000001d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=52,score_T4_Eq_jump=52] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.567341632d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.758333316d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=53,score_T4_Eq_jump=53] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.578252048d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.772916649d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=54,score_T4_Eq_jump=54] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.5891624639999999d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.787499982d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=55,score_T4_Eq_jump=55] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.6000728799999999d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.8020833150000001d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=56,score_T4_Eq_jump=56] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.6109832959999999d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.816666648d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=57,score_T4_Eq_jump=57] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.621893712d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.831249981d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=58,score_T4_Eq_jump=58] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.632804128d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.8458333140000001d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=59,score_T4_Eq_jump=59] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.6437145439999999d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.860416647d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}

entitydata @s[score_T4_Eq_jump_min=60] {ArmorItems:[{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"TesseractFour Equines Horse Speed Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Horse Jump Devaluation",Amount:-0.2d,Operation:2,UUIDLeast:1,UUIDMost:1},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Horse Health Devaluation",Amount:-0.1d,Operation:2,UUIDLeast:1,UUIDMost:1}]}},{id:"minecraft:barrier",Count:1b,Damage:0s,tag:{T4_traits:{isIllegal:1b},AttributeModifiers:[{AttributeName:"horse.jumpStrength",Name:"TesseractFour Equines Training Jump Bonus",Amount:0.6546249599999999d,Operation:2,UUIDLeast:6001,UUIDMost:7001},{AttributeName:"generic.maxHealth",Name:"TesseractFour Equines Training Health Bonus",Amount:0.87499998d,Operation:2,UUIDLeast:6001,UUIDMost:7001}]}},{},{}]}
