# (C) TesseractFour by ChocoParrot, 2017
# All rights reserved
# Cave-In by ChocoParrot
scoreboard players add @e[type=falling_block,tag=T4_CI_isFalling] T4_CI_falltime 1

execute @e[type=falling_block,tag=T4_CI_fall,score_T4_CI_falltime=4] ~-1 ~ ~ detect ~ ~ ~ stone 0 execute @s ~-1 ~ ~ detect ~ ~-1 ~ air -1 summon minecraft:falling_block ~ ~-0.05 ~ {DropItem:0b,TileID:1,Time:0s,Tags:["T4_CI_fall","T4_CI_isFalling","T4_CI_sound"],FallHurtAmount:8.0f,FallHurtMax:20,HurtEntities:1b}
execute @e[type=falling_block,tag=T4_CI_fall,score_T4_CI_falltime=4] ~1 ~ ~ detect ~ ~ ~ stone 0 execute @s ~1 ~ ~ detect ~ ~-1 ~ air -1 summon minecraft:falling_block ~ ~-0.05 ~ {DropItem:0b,TileID:1,Time:0s,Tags:["T4_CI_fall","T4_CI_isFalling","T4_CI_sound"],FallHurtAmount:8.0f,FallHurtMax:20,HurtEntities:1b}
execute @e[type=falling_block,tag=T4_CI_fall,score_T4_CI_falltime=4] ~ ~ ~1 detect ~ ~ ~ stone 0 execute @s ~ ~ ~1 detect ~ ~-1 ~ air -1 summon minecraft:falling_block ~ ~-0.05 ~ {DropItem:0b,TileID:1,Time:0s,Tags:["T4_CI_fall","T4_CI_isFalling","T4_CI_sound"],FallHurtAmount:8.0f,FallHurtMax:20,HurtEntities:1b}
execute @e[type=falling_block,tag=T4_CI_fall,score_T4_CI_falltime=4] ~ ~ ~-1 detect ~ ~ ~ stone 0 execute @s ~ ~ ~-1 detect ~ ~-1 ~ air -1 summon minecraft:falling_block ~ ~-0.05 ~ {DropItem:0b,TileID:1,Time:0s,Tags:["T4_CI_fall","T4_CI_isFalling","T4_CI_sound"],FallHurtAmount:8.0f,FallHurtMax:20,HurtEntities:1b}

execute @e[type=falling_block,tag=T4_CI_fall,score_T4_CI_falltime=4] ~-1 ~ ~ detect ~ ~ ~ stone 1 execute @s ~-1 ~ ~ detect ~ ~-1 ~ air -1 summon minecraft:falling_block ~ ~-0.05 ~ {DropItem:0b,TileID:1,Time:0s,Tags:["T4_CI_fall","T4_CI_isFalling","T4_CI_sound"],FallHurtAmount:14.0f,FallHurtMax:40,HurtEntities:1b,Data:1}
execute @e[type=falling_block,tag=T4_CI_fall,score_T4_CI_falltime=4] ~1 ~ ~ detect ~ ~ ~ stone 1 execute @s ~1 ~ ~ detect ~ ~-1 ~ air -1 summon minecraft:falling_block ~ ~-0.05 ~ {DropItem:0b,TileID:1,Time:0s,Tags:["T4_CI_fall","T4_CI_isFalling","T4_CI_sound"],FallHurtAmount:14.0f,FallHurtMax:40,HurtEntities:1b,Data:1}
execute @e[type=falling_block,tag=T4_CI_fall,score_T4_CI_falltime=4] ~ ~ ~1 detect ~ ~ ~ stone 1 execute @s ~ ~ ~1 detect ~ ~-1 ~ air -1 summon minecraft:falling_block ~ ~-0.05 ~ {DropItem:0b,TileID:1,Time:0s,Tags:["T4_CI_fall","T4_CI_isFalling","T4_CI_sound"],FallHurtAmount:14.0f,FallHurtMax:40,HurtEntities:1b,Data:1}
execute @e[type=falling_block,tag=T4_CI_fall,score_T4_CI_falltime=4] ~ ~ ~-1 detect ~ ~ ~ stone 1 execute @s ~ ~ ~-1 detect ~ ~-1 ~ air -1 summon minecraft:falling_block ~ ~-0.05 ~ {DropItem:0b,TileID:1,Time:0s,Tags:["T4_CI_fall","T4_CI_isFalling","T4_CI_sound"],FallHurtAmount:14.0f,FallHurtMax:40,HurtEntities:1b,Data:1}

execute @e[type=falling_block,tag=T4_CI_fall,score_T4_CI_falltime=4] ~-1 ~ ~ detect ~ ~ ~ stone 3 execute @s ~-1 ~ ~ detect ~ ~-1 ~ air -1 summon minecraft:falling_block ~ ~-0.05 ~ {DropItem:0b,TileID:1,Time:0s,Tags:["T4_CI_fall","T4_CI_isFalling","T4_CI_sound"],FallHurtAmount:17.0f,FallHurtMax:50,HurtEntities:1b,Data:3}
execute @e[type=falling_block,tag=T4_CI_fall,score_T4_CI_falltime=4] ~1 ~ ~ detect ~ ~ ~ stone 3 execute @s ~1 ~ ~ detect ~ ~-1 ~ air -1 summon minecraft:falling_block ~ ~-0.05 ~ {DropItem:0b,TileID:1,Time:0s,Tags:["T4_CI_fall","T4_CI_isFalling","T4_CI_sound"],FallHurtAmount:17.0f,FallHurtMax:50,HurtEntities:1b,Data:3}
execute @e[type=falling_block,tag=T4_CI_fall,score_T4_CI_falltime=4] ~ ~ ~1 detect ~ ~ ~ stone 3 execute @s ~ ~ ~1 detect ~ ~-1 ~ air -1 summon minecraft:falling_block ~ ~-0.05 ~ {DropItem:0b,TileID:1,Time:0s,Tags:["T4_CI_fall","T4_CI_isFalling","T4_CI_sound"],FallHurtAmount:17.0f,FallHurtMax:50,HurtEntities:1b,Data:3}
execute @e[type=falling_block,tag=T4_CI_fall,score_T4_CI_falltime=4] ~ ~ ~-1 detect ~ ~ ~ stone 3 execute @s ~ ~ ~-1 detect ~ ~-1 ~ air -1 summon minecraft:falling_block ~ ~-0.05 ~ {DropItem:0b,TileID:1,Time:0s,Tags:["T4_CI_fall","T4_CI_isFalling","T4_CI_sound"],FallHurtAmount:17.0f,FallHurtMax:50,HurtEntities:1b,Data:3}

execute @e[type=falling_block,tag=T4_CI_fall,score_T4_CI_falltime=4] ~-1 ~ ~ detect ~ ~ ~ stone 5 execute @s ~-1 ~ ~ detect ~ ~-1 ~ air -1 summon minecraft:falling_block ~ ~-0.05 ~ {DropItem:0b,TileID:1,Time:0s,Tags:["T4_CI_fall","T4_CI_isFalling","T4_CI_sound"],FallHurtAmount:11.0f,FallHurtMax:30,HurtEntities:1b,Data:5}
execute @e[type=falling_block,tag=T4_CI_fall,score_T4_CI_falltime=4] ~1 ~ ~ detect ~ ~ ~ stone 5 execute @s ~1 ~ ~ detect ~ ~-1 ~ air -1 summon minecraft:falling_block ~ ~-0.05 ~ {DropItem:0b,TileID:1,Time:0s,Tags:["T4_CI_fall","T4_CI_isFalling","T4_CI_sound"],FallHurtAmount:11.0f,FallHurtMax:30,HurtEntities:1b,Data:5}
execute @e[type=falling_block,tag=T4_CI_fall,score_T4_CI_falltime=4] ~ ~ ~1 detect ~ ~ ~ stone 5 execute @s ~ ~ ~1 detect ~ ~-1 ~ air -1 summon minecraft:falling_block ~ ~-0.05 ~ {DropItem:0b,TileID:1,Time:0s,Tags:["T4_CI_fall","T4_CI_isFalling","T4_CI_sound"],FallHurtAmount:11.0f,FallHurtMax:30,HurtEntities:1b,Data:5}
execute @e[type=falling_block,tag=T4_CI_fall,score_T4_CI_falltime=4] ~ ~ ~-1 detect ~ ~ ~ stone 5 execute @s ~ ~ ~-1 detect ~ ~-1 ~ air -1 summon minecraft:falling_block ~ ~-0.05 ~ {DropItem:0b,TileID:1,Time:0s,Tags:["T4_CI_fall","T4_CI_isFalling","T4_CI_sound"],FallHurtAmount:11.0f,FallHurtMax:30,HurtEntities:1b,Data:5}

execute @e[type=falling_block,tag=T4_CI_fall,score_T4_CI_falltime=4] ~-1 ~ ~ detect ~ ~ ~ dirt 0 execute @s ~-1 ~ ~ detect ~ ~-1 ~ air -1 summon minecraft:falling_block ~ ~-0.05 ~ {DropItem:0b,TileID:3,Time:0s,Tags:["T4_CI_fall","T4_CI_isFalling","T4_CI_sound"],FallHurtAmount:6.0f,FallHurtMax:18,HurtEntities:1b}
execute @e[type=falling_block,tag=T4_CI_fall,score_T4_CI_falltime=4] ~1 ~ ~ detect ~ ~ ~ dirt 0 execute @s ~1 ~ ~ detect ~ ~-1 ~ air -1 summon minecraft:falling_block ~ ~-0.05 ~ {DropItem:0b,TileID:3,Time:0s,Tags:["T4_CI_fall","T4_CI_isFalling","T4_CI_sound"],FallHurtAmount:6.0f,FallHurtMax:18,HurtEntities:1b}
execute @e[type=falling_block,tag=T4_CI_fall,score_T4_CI_falltime=4] ~ ~ ~1 detect ~ ~ ~ dirt 0 execute @s ~ ~ ~1 detect ~ ~-1 ~ air -1 summon minecraft:falling_block ~ ~-0.05 ~ {DropItem:0b,TileID:3,Time:0s,Tags:["T4_CI_fall","T4_CI_isFalling","T4_CI_sound"],FallHurtAmount:6.0f,FallHurtMax:18,HurtEntities:1b}
execute @e[type=falling_block,tag=T4_CI_fall,score_T4_CI_falltime=4] ~ ~ ~-1 detect ~ ~ ~ dirt 0 execute @s ~ ~ ~-1 detect ~ ~-1 ~ air -1 summon minecraft:falling_block ~ ~-0.05 ~ {DropItem:0b,TileID:3,Time:0s,Tags:["T4_CI_fall","T4_CI_isFalling","T4_CI_sound"],FallHurtAmount:6.0f,FallHurtMax:18,HurtEntities:1b}

execute @e[type=falling_block,tag=T4_CI_fall,score_T4_CI_falltime=4] ~-1 ~ ~ detect ~ ~ ~ cobblestone 0 execute @s ~-1 ~ ~ detect ~ ~-1 ~ air -1 summon minecraft:falling_block ~ ~-0.05 ~ {DropItem:0b,TileID:4,Time:0s,Tags:["T4_CI_fall","T4_CI_isFalling","T4_CI_sound"],FallHurtAmount:6.0f,FallHurtMax:18,HurtEntities:1b}
execute @e[type=falling_block,tag=T4_CI_fall,score_T4_CI_falltime=4] ~1 ~ ~ detect ~ ~ ~ cobblestone 0 execute @s ~1 ~ ~ detect ~ ~-1 ~ air -1 summon minecraft:falling_block ~ ~-0.05 ~ {DropItem:0b,TileID:4,Time:0s,Tags:["T4_CI_fall","T4_CI_isFalling","T4_CI_sound"],FallHurtAmount:6.0f,FallHurtMax:18,HurtEntities:1b}
execute @e[type=falling_block,tag=T4_CI_fall,score_T4_CI_falltime=4] ~ ~ ~1 detect ~ ~ ~ cobblestone 0 execute @s ~ ~ ~1 detect ~ ~-1 ~ air -1 summon minecraft:falling_block ~ ~-0.05 ~ {DropItem:0b,TileID:4,Time:0s,Tags:["T4_CI_fall","T4_CI_isFalling","T4_CI_sound"],FallHurtAmount:6.0f,FallHurtMax:18,HurtEntities:1b}
execute @e[type=falling_block,tag=T4_CI_fall,score_T4_CI_falltime=4] ~ ~ ~-1 detect ~ ~ ~ cobblestone 0 execute @s ~ ~ ~-1 detect ~ ~-1 ~ air -1 summon minecraft:falling_block ~ ~-0.05 ~ {DropItem:0b,TileID:4,Time:0s,Tags:["T4_CI_fall","T4_CI_isFalling","T4_CI_sound"],FallHurtAmount:6.0f,FallHurtMax:18,HurtEntities:1b}

execute @e[score_T4_CI_falltime_min=1,score_T4_CI_falltime=1,tag=T4_CI_sound] ~ ~ ~ playsound entity.zombie.break_door_wood block @a ~ ~ ~ 0.05 0
