# (C) TesseractFour by ChocoParrot, 2017
# All rights reserved
# Timberjack by ChocoParrot
# Inspired by the Timberjack Mod by CovertJaguar

scoreboard players add @e[tag=T4_T_f1] T4_T_ltime 1

execute @e[tag=T4_T_f1,score_T4_T_ltime_min=1,score_T4_T_ltime=2,type=falling_block] ~1 ~ ~ detect ~ ~ ~ leaves variant=oak summon falling_block ~ ~ ~ {DropItem:0b,TileID:18,Data:0,Time:0s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:13,HurtEntities:1b}
execute @e[tag=T4_T_f1,score_T4_T_ltime_min=1,score_T4_T_ltime=2,type=falling_block] ~ ~ ~1 detect ~ ~ ~ leaves variant=oak summon falling_block ~ ~ ~ {DropItem:0b,TileID:18,Data:0,Time:0s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:13,HurtEntities:1b}
execute @e[tag=T4_T_f1,score_T4_T_ltime_min=1,score_T4_T_ltime=2,type=falling_block] ~-1 ~ ~ detect ~ ~ ~ leaves variant=oak summon falling_block ~ ~ ~ {DropItem:0b,TileID:18,Data:0,Time:0s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:13,HurtEntities:1b}
execute @e[tag=T4_T_f1,score_T4_T_ltime_min=1,score_T4_T_ltime=2,type=falling_block] ~ ~ ~-1 detect ~ ~ ~ leaves variant=oak summon falling_block ~ ~ ~ {DropItem:0b,TileID:18,Data:0,Time:0s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:13,HurtEntities:1b}

execute @e[tag=T4_T_f1,score_T4_T_ltime_min=1,score_T4_T_ltime=2,type=falling_block] ~1 ~ ~ detect ~ ~ ~ leaves variant=spruce summon falling_block ~ ~ ~ {DropItem:0b,TileID:18,Data:1,Time:0s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:14,HurtEntities:1b,Passengers:[{id:"minecraft:potion",Potion:{id:"minecraft:splash_potion",Count:1b,tag:{Potion:"minecraft:harming",CustomPotionEffects:[{Id:7,Duration:1000,Amplifier:0b,Ambient:0b,ShowParticles:0b}]}}}]}
execute @e[tag=T4_T_f1,score_T4_T_ltime_min=1,score_T4_T_ltime=2,type=falling_block] ~ ~ ~1 detect ~ ~ ~ leaves variant=spruce summon falling_block ~ ~ ~ {DropItem:0b,TileID:18,Data:1,Time:0s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:14,HurtEntities:1b,Passengers:[{id:"minecraft:potion",Potion:{id:"minecraft:splash_potion",Count:1b,tag:{Potion:"minecraft:harming",CustomPotionEffects:[{Id:7,Duration:1000,Amplifier:0b,Ambient:0b,ShowParticles:0b}]}}}]}
execute @e[tag=T4_T_f1,score_T4_T_ltime_min=1,score_T4_T_ltime=2,type=falling_block] ~-1 ~ ~ detect ~ ~ ~ leaves variant=spruce summon falling_block ~ ~ ~ {DropItem:0b,TileID:18,Data:1,Time:0s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:14,HurtEntities:1b,Passengers:[{id:"minecraft:potion",Potion:{id:"minecraft:splash_potion",Count:1b,tag:{Potion:"minecraft:harming",CustomPotionEffects:[{Id:7,Duration:1000,Amplifier:0b,Ambient:0b,ShowParticles:0b}]}}}]}
execute @e[tag=T4_T_f1,score_T4_T_ltime_min=1,score_T4_T_ltime=2,type=falling_block] ~ ~ ~-1 detect ~ ~ ~ leaves variant=spruce summon falling_block ~ ~ ~ {DropItem:0b,TileID:18,Data:1,Time:0s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:14,HurtEntities:1b,Passengers:[{id:"minecraft:potion",Potion:{id:"minecraft:splash_potion",Count:1b,tag:{Potion:"minecraft:harming",CustomPotionEffects:[{Id:7,Duration:1000,Amplifier:0b,Ambient:0b,ShowParticles:0b}]}}}]}

execute @e[tag=T4_T_f1,score_T4_T_ltime_min=1,score_T4_T_ltime=2,type=falling_block] ~1 ~ ~ detect ~ ~ ~ leaves variant=birch summon falling_block ~ ~ ~ {DropItem:0b,TileID:18,Data:2,Time:0s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:13,HurtEntities:1b}
execute @e[tag=T4_T_f1,score_T4_T_ltime_min=1,score_T4_T_ltime=2,type=falling_block] ~ ~ ~1 detect ~ ~ ~ leaves variant=birch summon falling_block ~ ~ ~ {DropItem:0b,TileID:18,Data:2,Time:0s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:13,HurtEntities:1b}
execute @e[tag=T4_T_f1,score_T4_T_ltime_min=1,score_T4_T_ltime=2,type=falling_block] ~-1 ~ ~ detect ~ ~ ~ leaves variant=birch summon falling_block ~ ~ ~ {DropItem:0b,TileID:18,Data:2,Time:0s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:13,HurtEntities:1b}
execute @e[tag=T4_T_f1,score_T4_T_ltime_min=1,score_T4_T_ltime=2,type=falling_block] ~ ~ ~-1 detect ~ ~ ~ leaves variant=birch summon falling_block ~ ~ ~ {DropItem:0b,TileID:18,Data:2,Time:0s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:13,HurtEntities:1b}

execute @e[tag=T4_T_f1,score_T4_T_ltime_min=1,score_T4_T_ltime=2,type=falling_block] ~1 ~ ~ detect ~ ~ ~ leaves variant=jungle summon falling_block ~ ~ ~ {DropItem:0b,TileID:18,Data:3,Time:0s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:14,HurtEntities:1b}
execute @e[tag=T4_T_f1,score_T4_T_ltime_min=1,score_T4_T_ltime=2,type=falling_block] ~ ~ ~1 detect ~ ~ ~ leaves variant=jungle summon falling_block ~ ~ ~ {DropItem:0b,TileID:18,Data:3,Time:0s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:14,HurtEntities:1b}
execute @e[tag=T4_T_f1,score_T4_T_ltime_min=1,score_T4_T_ltime=2,type=falling_block] ~-1 ~ ~ detect ~ ~ ~ leaves variant=jungle summon falling_block ~ ~ ~ {DropItem:0b,TileID:18,Data:3,Time:0s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:14,HurtEntities:1b}
execute @e[tag=T4_T_f1,score_T4_T_ltime_min=1,score_T4_T_ltime=2,type=falling_block] ~ ~ ~-1 detect ~ ~ ~ leaves variant=jungle summon falling_block ~ ~ ~ {DropItem:0b,TileID:18,Data:3,Time:0s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:14,HurtEntities:1b}

execute @e[tag=T4_T_f1,score_T4_T_ltime_min=1,score_T4_T_ltime=2,type=falling_block] ~1 ~ ~ detect ~ ~ ~ leaves2 variant=acacia summon falling_block ~ ~ ~ {DropItem:0b,TileID:161,Data:0,Time:0s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:10,HurtEntities:1b}
execute @e[tag=T4_T_f1,score_T4_T_ltime_min=1,score_T4_T_ltime=2,type=falling_block] ~ ~ ~1 detect ~ ~ ~ leaves2 variant=acacia summon falling_block ~ ~ ~ {DropItem:0b,TileID:161,Data:0,Time:0s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:10,HurtEntities:1b}
execute @e[tag=T4_T_f1,score_T4_T_ltime_min=1,score_T4_T_ltime=2,type=falling_block] ~-1 ~ ~ detect ~ ~ ~ leaves2 variant=acacia summon falling_block ~ ~ ~ {DropItem:0b,TileID:161,Data:0,Time:0s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:10,HurtEntities:1b}
execute @e[tag=T4_T_f1,score_T4_T_ltime_min=1,score_T4_T_ltime=2,type=falling_block] ~ ~ ~-1 detect ~ ~ ~ leaves2 variant=acacia summon falling_block ~ ~ ~ {DropItem:0b,TileID:161,Data:0,Time:0s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:10,HurtEntities:1b}

execute @e[tag=T4_T_f1,score_T4_T_ltime_min=1,score_T4_T_ltime=2,type=falling_block] ~1 ~ ~ detect ~ ~ ~ leaves2 variant=dark_oak summon falling_block ~ ~ ~ {DropItem:0b,TileID:161,Data:1,Time:0s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:14,HurtEntities:1b}
execute @e[tag=T4_T_f1,score_T4_T_ltime_min=1,score_T4_T_ltime=2,type=falling_block] ~ ~ ~1 detect ~ ~ ~ leaves2 variant=dark_oak summon falling_block ~ ~ ~ {DropItem:0b,TileID:161,Data:1,Time:0s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:14,HurtEntities:1b}
execute @e[tag=T4_T_f1,score_T4_T_ltime_min=1,score_T4_T_ltime=2,type=falling_block] ~-1 ~ ~ detect ~ ~ ~ leaves2 variant=dark_oak summon falling_block ~ ~ ~ {DropItem:0b,TileID:161,Data:1,Time:0s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:14,HurtEntities:1b}
execute @e[tag=T4_T_f1,score_T4_T_ltime_min=1,score_T4_T_ltime=2,type=falling_block] ~ ~ ~-1 detect ~ ~ ~ leaves2 variant=dark_oak summon falling_block ~ ~ ~ {DropItem:0b,TileID:161,Data:1,Time:0s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:14,HurtEntities:1b}
