# (C) TesseractFour by ChocoParrot, 2017
# All rights reserved
# Timberjack by ChocoParrot
# Inspired by the Timberjack Mod by CovertJaguar

execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~ ~ detect ~ ~ ~ leaves variant=oak summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:18,Data:0,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:13,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~ ~ detect ~ ~ ~ leaves variant=spruce summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:18,Data:1,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:14,HurtEntities:1b,Passengers:[{id:"minecraft:potion",Potion:{id:"minecraft:splash_potion",Count:1b,tag:{Potion:"minecraft:harming",CustomPotionEffects:[{Id:7,Duration:10,Amplifier:0b,Ambient:0b,ShowParticles:0b}]}}}]}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~ ~ detect ~ ~ ~ leaves variant=birch summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:18,Data:2,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:13,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~ ~ detect ~ ~ ~ leaves variant=jungle summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:18,Data:3,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:14,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~ ~ detect ~ ~ ~ leaves -1 setblock ~ ~ ~ air 0
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~ ~ detect ~ ~ ~ leaves2 variant=acacia summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:161,Data:0,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:10,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~ ~ detect ~ ~ ~ leaves2 variant=dark_oak summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:161,Data:1,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:14,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~ ~ detect ~ ~ ~ leaves2 -1 setblock ~ ~ ~ air 0

execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~ ~1 detect ~ ~ ~ leaves variant=oak summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:18,Data:0,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:13,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~ ~1 detect ~ ~ ~ leaves variant=spruce summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:18,Data:1,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:14,HurtEntities:1b,Passengers:[{id:"minecraft:potion",Potion:{id:"minecraft:splash_potion",Count:1b,tag:{Potion:"minecraft:harming",CustomPotionEffects:[{Id:7,Duration:10,Amplifier:0b,Ambient:0b,ShowParticles:0b}]}}}]}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~ ~1 detect ~ ~ ~ leaves variant=birch summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:18,Data:2,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:13,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~ ~1 detect ~ ~ ~ leaves variant=jungle summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:18,Data:3,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:14,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~ ~1 detect ~ ~ ~ leaves -1 setblock ~ ~ ~ air 0
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~ ~1 detect ~ ~ ~ leaves2 variant=acacia summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:161,Data:0,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:10,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~ ~1 detect ~ ~ ~ leaves2 variant=dark_oak summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:161,Data:1,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:14,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~ ~1 detect ~ ~ ~ leaves2 -1 setblock ~ ~ ~ air 0

execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~ ~ detect ~ ~ ~ leaves variant=oak summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:18,Data:0,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:13,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~ ~ detect ~ ~ ~ leaves variant=spruce summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:18,Data:1,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:14,HurtEntities:1b,Passengers:[{id:"minecraft:potion",Potion:{id:"minecraft:splash_potion",Count:1b,tag:{Potion:"minecraft:harming",CustomPotionEffects:[{Id:7,Duration:10,Amplifier:0b,Ambient:0b,ShowParticles:0b}]}}}]}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~ ~ detect ~ ~ ~ leaves variant=birch summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:18,Data:2,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:13,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~ ~ detect ~ ~ ~ leaves variant=jungle summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:18,Data:3,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:14,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~ ~ detect ~ ~ ~ leaves -1 setblock ~ ~ ~ air 0
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~ ~ detect ~ ~ ~ leaves2 variant=acacia summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:161,Data:0,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:10,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~ ~ detect ~ ~ ~ leaves2 variant=dark_oak summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:161,Data:1,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:14,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~ ~ detect ~ ~ ~ leaves2 -1 setblock ~ ~ ~ air 0

execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~ ~-1 detect ~ ~ ~ leaves variant=oak summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:18,Data:0,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:13,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~ ~-1 detect ~ ~ ~ leaves variant=spruce summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:18,Data:1,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:14,HurtEntities:1b,Passengers:[{id:"minecraft:potion",Potion:{id:"minecraft:splash_potion",Count:1b,tag:{Potion:"minecraft:harming",CustomPotionEffects:[{Id:7,Duration:10,Amplifier:0b,Ambient:0b,ShowParticles:0b}]}}}]}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~ ~-1 detect ~ ~ ~ leaves variant=birch summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:18,Data:2,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:13,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~ ~-1 detect ~ ~ ~ leaves variant=jungle summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:18,Data:3,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:14,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~ ~-1 detect ~ ~ ~ leaves -1 setblock ~ ~ ~ air 0
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~ ~-1 detect ~ ~ ~ leaves2 variant=acacia summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:161,Data:0,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:10,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~ ~-1 detect ~ ~ ~ leaves2 variant=dark_oak summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:161,Data:1,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:14,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~ ~-1 detect ~ ~ ~ leaves2 -1 setblock ~ ~ ~ air 0

execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~1 ~ detect ~ ~ ~ leaves variant=oak summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:18,Data:0,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:13,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~1 ~ detect ~ ~ ~ leaves variant=spruce summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:18,Data:1,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:14,HurtEntities:1b,Passengers:[{id:"minecraft:potion",Potion:{id:"minecraft:splash_potion",Count:1b,tag:{Potion:"minecraft:harming",CustomPotionEffects:[{Id:7,Duration:10,Amplifier:0b,Ambient:0b,ShowParticles:0b}]}}}]}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~1 ~ detect ~ ~ ~ leaves variant=birch summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:18,Data:2,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:13,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~1 ~ detect ~ ~ ~ leaves variant=jungle summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:18,Data:3,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:14,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~1 ~ detect ~ ~ ~ leaves -1 setblock ~ ~ ~ air 0
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~1 ~ detect ~ ~ ~ leaves2 variant=acacia summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:161,Data:0,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:10,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~1 ~ detect ~ ~ ~ leaves2 variant=dark_oak summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:161,Data:1,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:14,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~1 ~ detect ~ ~ ~ leaves2 -1 setblock ~ ~ ~ air 0

execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~2 ~ detect ~ ~ ~ leaves variant=oak summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:18,Data:0,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:13,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~2 ~ detect ~ ~ ~ leaves variant=spruce summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:18,Data:1,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:14,HurtEntities:1b,Passengers:[{id:"minecraft:potion",Potion:{id:"minecraft:splash_potion",Count:1b,tag:{Potion:"minecraft:harming",CustomPotionEffects:[{Id:7,Duration:10,Amplifier:0b,Ambient:0b,ShowParticles:0b}]}}}]}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~2 ~ detect ~ ~ ~ leaves variant=birch summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:18,Data:2,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:13,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~2 ~ detect ~ ~ ~ leaves variant=jungle summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:18,Data:3,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:14,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~2 ~ detect ~ ~ ~ leaves -1 setblock ~ ~ ~ air 0
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~2 ~ detect ~ ~ ~ leaves2 variant=acacia summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:161,Data:0,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:10,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~2 ~ detect ~ ~ ~ leaves2 variant=dark_oak summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:161,Data:1,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:14,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~2 ~ detect ~ ~ ~ leaves2 -1 setblock ~ ~ ~ air 0

execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~3 ~ detect ~ ~ ~ leaves variant=oak summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:18,Data:0,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:13,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~3 ~ detect ~ ~ ~ leaves variant=spruce summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:18,Data:1,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:14,HurtEntities:1b,Passengers:[{id:"minecraft:potion",Potion:{id:"minecraft:splash_potion",Count:1b,tag:{Potion:"minecraft:harming",CustomPotionEffects:[{Id:7,Duration:10,Amplifier:0b,Ambient:0b,ShowParticles:0b}]}}}]}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~3 ~ detect ~ ~ ~ leaves variant=birch summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:18,Data:2,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:13,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~3 ~ detect ~ ~ ~ leaves variant=jungle summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:18,Data:3,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:14,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~3 ~ detect ~ ~ ~ leaves -1 setblock ~ ~ ~ air 0
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~3 ~ detect ~ ~ ~ leaves2 variant=acacia summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:161,Data:0,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:10,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~3 ~ detect ~ ~ ~ leaves2 variant=dark_oak summon falling_block ~ ~0.2 ~ {DropItem:0b,TileID:161,Data:1,Time:1s,Tags:["T4_T_f1","T4_T_leaves"],FallHurtAmount:2.0f,FallHurtMax:14,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~3 ~ detect ~ ~ ~ leaves2 -1 setblock ~ ~ ~ air 0
