# (C) TesseractFour by ChocoParrot, 2017
# All rights reserved
# Timberjack by ChocoParrot
# Inspired by the Timberjack Mod by CovertJaguar

execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~ ~-1 detect ~ ~ ~ log axis=y,variant=oak execute @s ~-1 ~ ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~ ~-1 detect ~ ~ ~ log axis=y,variant=spruce execute @s ~-1 ~ ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~ ~-1 detect ~ ~ ~ log axis=y,variant=birch execute @s ~-1 ~ ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:2,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~ ~-1 detect ~ ~ ~ log axis=y,variant=jungle execute @s ~-1 ~ ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:3,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~ ~-1 detect ~ ~ ~ log axis=y execute @s ~-1 ~ ~-1 detect ~ ~-1 ~ air -1 setblock ~ ~ ~ air 0
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~ ~-1 detect ~ ~ ~ log2 axis=y,variant=acacia execute @s ~-1 ~ ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~ ~-1 detect ~ ~ ~ log2 axis=y,variant=dark_oak execute @s ~-1 ~ ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~ ~-1 detect ~ ~ ~ log2 axis=y execute @s ~-1 ~ ~-1 detect ~ ~-1 ~ air -1 setblock ~ ~ ~ air 0

execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~ ~-1 detect ~ ~ ~ log axis=y,variant=oak execute @s ~1 ~ ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~ ~-1 detect ~ ~ ~ log axis=y,variant=spruce execute @s ~1 ~ ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~ ~-1 detect ~ ~ ~ log axis=y,variant=birch execute @s ~1 ~ ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:2,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~ ~-1 detect ~ ~ ~ log axis=y,variant=jungle execute @s ~1 ~ ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:3,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~ ~-1 detect ~ ~ ~ log axis=y execute @s ~1 ~ ~-1 detect ~ ~-1 ~ air -1 setblock ~ ~ ~ air 0
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~ ~-1 detect ~ ~ ~ log2 axis=y,variant=acacia execute @s ~1 ~ ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~ ~-1 detect ~ ~ ~ log2 axis=y,variant=dark_oak execute @s ~1 ~ ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~ ~-1 detect ~ ~ ~ log2 axis=y execute @s ~1 ~ ~-1 detect ~ ~-1 ~ air -1 setblock ~ ~ ~ air 0

execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~ ~1 detect ~ ~ ~ log axis=y,variant=oak execute @s ~-1 ~ ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~ ~1 detect ~ ~ ~ log axis=y,variant=spruce execute @s ~-1 ~ ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~ ~1 detect ~ ~ ~ log axis=y,variant=birch execute @s ~-1 ~ ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:2,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~ ~1 detect ~ ~ ~ log axis=y,variant=jungle execute @s ~-1 ~ ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:3,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~ ~1 detect ~ ~ ~ log axis=y execute @s ~-1 ~ ~1 detect ~ ~-1 ~ air -1 setblock ~ ~ ~ air 0
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~ ~1 detect ~ ~ ~ log2 axis=y,variant=acacia execute @s ~-1 ~ ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~ ~1 detect ~ ~ ~ log2 axis=y,variant=dark_oak execute @s ~-1 ~ ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~ ~1 detect ~ ~ ~ log2 axis=y execute @s ~-1 ~ ~1 detect ~ ~-1 ~ air -1 setblock ~ ~ ~ air 0

execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~ ~1 detect ~ ~ ~ log axis=y,variant=oak execute @s ~1 ~ ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~ ~1 detect ~ ~ ~ log axis=y,variant=spruce execute @s ~1 ~ ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~ ~1 detect ~ ~ ~ log axis=y,variant=birch execute @s ~1 ~ ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:2,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~ ~1 detect ~ ~ ~ log axis=y,variant=jungle execute @s ~1 ~ ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:3,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~ ~1 detect ~ ~ ~ log axis=y execute @s ~1 ~ ~1 detect ~ ~-1 ~ air -1 setblock ~ ~ ~ air 0
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~ ~1 detect ~ ~ ~ log2 axis=y,variant=acacia execute @s ~1 ~ ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~ ~1 detect ~ ~ ~ log2 axis=y,variant=dark_oak execute @s ~1 ~ ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~ ~1 detect ~ ~ ~ log2 axis=y execute @s ~1 ~ ~1 detect ~ ~-1 ~ air -1 setblock ~ ~ ~ air 0

execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~ ~ detect ~ ~ ~ log axis=y,variant=oak execute @s ~-1 ~ ~ detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~ ~ detect ~ ~ ~ log axis=y,variant=spruce execute @s ~-1 ~ ~ detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~ ~ detect ~ ~ ~ log axis=y,variant=birch execute @s ~-1 ~ ~ detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:2,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~ ~ detect ~ ~ ~ log axis=y,variant=jungle execute @s ~-1 ~ ~ detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:3,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~ ~ detect ~ ~ ~ log axis=y execute @s ~-1 ~ ~ detect ~ ~-1 ~ air -1 setblock ~ ~ ~ air 0
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~ ~ detect ~ ~ ~ log2 axis=y,variant=acacia execute @s ~-1 ~ ~ detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~ ~ detect ~ ~ ~ log2 axis=y,variant=dark_oak execute @s ~-1 ~ ~ detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~ ~ detect ~ ~ ~ log2 axis=y execute @s ~-1 ~ ~ detect ~ ~-1 ~ air -1 setblock ~ ~ ~ air 0

execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~ ~-1 detect ~ ~ ~ log axis=y,variant=oak execute @s ~ ~ ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~ ~-1 detect ~ ~ ~ log axis=y,variant=spruce execute @s ~ ~ ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~ ~-1 detect ~ ~ ~ log axis=y,variant=birch execute @s ~ ~ ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:2,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~ ~-1 detect ~ ~ ~ log axis=y,variant=jungle execute @s ~ ~ ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:3,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~ ~-1 detect ~ ~ ~ log axis=y execute @s ~ ~ ~-1 detect ~ ~-1 ~ air -1 setblock ~ ~ ~ air 0
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~ ~-1 detect ~ ~ ~ log2 axis=y,variant=acacia execute @s ~ ~ ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~ ~-1 detect ~ ~ ~ log2 axis=y,variant=dark_oak execute @s ~ ~ ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~ ~-1 detect ~ ~ ~ log2 axis=y execute @s ~ ~ ~-1 detect ~ ~-1 ~ air -1 setblock ~ ~ ~ air 0

execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~ ~ detect ~ ~ ~ log axis=y,variant=oak execute @s ~1 ~ ~ detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~ ~ detect ~ ~ ~ log axis=y,variant=spruce execute @s ~1 ~ ~ detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~ ~ detect ~ ~ ~ log axis=y,variant=birch execute @s ~1 ~ ~ detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:2,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~ ~ detect ~ ~ ~ log axis=y,variant=jungle execute @s ~1 ~ ~ detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:3,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~ ~ detect ~ ~ ~ log axis=y execute @s ~1 ~ ~ detect ~ ~-1 ~ air -1 setblock ~ ~ ~ air 0
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~ ~ detect ~ ~ ~ log2 axis=y,variant=acacia execute @s ~1 ~ ~ detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~ ~ detect ~ ~ ~ log2 axis=y,variant=dark_oak execute @s ~1 ~ ~ detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~ ~ detect ~ ~ ~ log2 axis=y execute @s ~1 ~ ~ detect ~ ~-1 ~ air -1 setblock ~ ~ ~ air 0

execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~ ~1 detect ~ ~ ~ log axis=y,variant=oak execute @s ~ ~ ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~ ~1 detect ~ ~ ~ log axis=y,variant=spruce execute @s ~ ~ ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~ ~1 detect ~ ~ ~ log axis=y,variant=birch execute @s ~ ~ ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:2,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~ ~1 detect ~ ~ ~ log axis=y,variant=jungle execute @s ~ ~ ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:3,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~ ~1 detect ~ ~ ~ log axis=y execute @s ~ ~ ~1 detect ~ ~-1 ~ air -1 setblock ~ ~ ~ air 0
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~ ~1 detect ~ ~ ~ log2 axis=y,variant=acacia execute @s ~ ~ ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~ ~1 detect ~ ~ ~ log2 axis=y,variant=dark_oak execute @s ~ ~ ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~ ~1 detect ~ ~ ~ log2 axis=y execute @s ~ ~ ~1 detect ~ ~-1 ~ air -1 setblock ~ ~ ~ air 0

# L2
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~1 ~-1 detect ~ ~ ~ log axis=y,variant=oak execute @s ~-1 ~1 ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~1 ~-1 detect ~ ~ ~ log axis=y,variant=spruce execute @s ~-1 ~1 ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~1 ~-1 detect ~ ~ ~ log axis=y,variant=birch execute @s ~-1 ~1 ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:2,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~1 ~-1 detect ~ ~ ~ log axis=y,variant=jungle execute @s ~-1 ~1 ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:3,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~1 ~-1 detect ~ ~ ~ log axis=y execute @s ~-1 ~ ~-1 detect ~ ~-1 ~ air -1 setblock ~ ~ ~ air 0
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~1 ~-1 detect ~ ~ ~ log2 axis=y,variant=acacia execute @s ~-1 ~1 ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~1 ~-1 detect ~ ~ ~ log2 axis=y,variant=dark_oak execute @s ~-1 ~1 ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~1 ~-1 detect ~ ~ ~ log2 axis=y execute @s ~-1 ~1 ~-1 detect ~ ~-1 ~ air -1 setblock ~ ~ ~ air 0

execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~1 ~-1 detect ~ ~ ~ log axis=y,variant=oak execute @s ~1 ~1 ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~1 ~-1 detect ~ ~ ~ log axis=y,variant=spruce execute @s ~1 ~1 ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~1 ~-1 detect ~ ~ ~ log axis=y,variant=birch execute @s ~1 ~1 ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:2,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~1 ~-1 detect ~ ~ ~ log axis=y,variant=jungle execute @s ~1 ~1 ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:3,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~1 ~-1 detect ~ ~ ~ log axis=y execute @s ~1 ~1 ~-1 detect ~ ~-1 ~ air -1 setblock ~ ~ ~ air 0
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~1 ~-1 detect ~ ~ ~ log2 axis=y,variant=acacia execute @s ~1 ~1 ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~1 ~-1 detect ~ ~ ~ log2 axis=y,variant=dark_oak execute @s ~1 ~1 ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~1 ~-1 detect ~ ~ ~ log2 axis=y execute @s ~1 ~1 ~-1 detect ~ ~-1 ~ air -1 setblock ~ ~ ~ air 0

execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~1 ~1 detect ~ ~ ~ log axis=y,variant=oak execute @s ~-1 ~1 ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~1 ~1 detect ~ ~ ~ log axis=y,variant=spruce execute @s ~-1 ~1 ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~1 ~1 detect ~ ~ ~ log axis=y,variant=birch execute @s ~-1 ~1 ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:2,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~1 ~1 detect ~ ~ ~ log axis=y,variant=jungle execute @s ~-1 ~1 ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:3,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~1 ~1 detect ~ ~ ~ log axis=y execute @s ~-1 ~1 ~1 detect ~ ~-1 ~ air -1 setblock ~ ~ ~ air 0
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~1 ~1 detect ~ ~ ~ log2 axis=y,variant=acacia execute @s ~-1 ~1 ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~1 ~1 detect ~ ~ ~ log2 axis=y,variant=dark_oak execute @s ~-1 ~1 ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~1 ~1 detect ~ ~ ~ log2 axis=y execute @s ~-1 ~1 ~1 detect ~ ~-1 ~ air -1 setblock ~ ~ ~ air 0

execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~1 ~1 detect ~ ~ ~ log axis=y,variant=oak execute @s ~1 ~1 ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~1 ~1 detect ~ ~ ~ log axis=y,variant=spruce execute @s ~1 ~1 ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~1 ~1 detect ~ ~ ~ log axis=y,variant=birch execute @s ~1 ~1 ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:2,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~1 ~1 detect ~ ~ ~ log axis=y,variant=jungle execute @s ~1 ~1 ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:3,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~1 ~1 detect ~ ~ ~ log axis=y execute @s ~1 ~1 ~1 detect ~ ~-1 ~ air -1 setblock ~ ~ ~ air 0
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~1 ~1 detect ~ ~ ~ log2 axis=y,variant=acacia execute @s ~1 ~1 ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~1 ~1 detect ~ ~ ~ log2 axis=y,variant=dark_oak execute @s ~1 ~1 ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~1 ~1 detect ~ ~ ~ log2 axis=y execute @s ~1 ~1 ~1 detect ~ ~-1 ~ air -1 setblock ~ ~ ~ air 0

execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~1 ~ detect ~ ~ ~ log axis=y,variant=oak execute @s ~-1 ~1 ~ detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~1 ~ detect ~ ~ ~ log axis=y,variant=spruce execute @s ~-1 ~1 ~ detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~1 ~ detect ~ ~ ~ log axis=y,variant=birch execute @s ~-1 ~1 ~ detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:2,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~1 ~ detect ~ ~ ~ log axis=y,variant=jungle execute @s ~-1 ~1 ~ detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:3,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~1 ~ detect ~ ~ ~ log axis=y execute @s ~-1 ~1 ~ detect ~ ~-1 ~ air -1 setblock ~ ~ ~ air 0
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~1 ~ detect ~ ~ ~ log2 axis=y,variant=acacia execute @s ~-1 ~1 ~ detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~1 ~ detect ~ ~ ~ log2 axis=y,variant=dark_oak execute @s ~-1 ~1 ~ detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~-1 ~1 ~ detect ~ ~ ~ log2 axis=y execute @s ~-1 ~1 ~ detect ~ ~-1 ~ air -1 setblock ~ ~ ~ air 0

execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~1 ~-1 detect ~ ~ ~ log axis=y,variant=oak execute @s ~ ~1 ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~1 ~-1 detect ~ ~ ~ log axis=y,variant=spruce execute @s ~1 ~ ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~1 ~-1 detect ~ ~ ~ log axis=y,variant=birch execute @s ~ ~1 ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:2,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~1 ~-1 detect ~ ~ ~ log axis=y,variant=jungle execute @s ~ ~1 ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:3,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~1 ~-1 detect ~ ~ ~ log axis=y execute @s ~ ~1 ~-1 detect ~ ~-1 ~ air -1 setblock ~ ~ ~ air 0
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~1 ~-1 detect ~ ~ ~ log2 axis=y,variant=acacia execute @s ~ ~1 ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~1 ~-1 detect ~ ~ ~ log2 axis=y,variant=dark_oak execute @s ~ ~1 ~-1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~1 ~-1 detect ~ ~ ~ log2 axis=y execute @s ~ ~1 ~-1 detect ~ ~-1 ~ air -1 setblock ~ ~ ~ air 0

execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~1 ~ detect ~ ~ ~ log axis=y,variant=oak execute @s ~1 ~1 ~ detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~1 ~ detect ~ ~ ~ log axis=y,variant=spruce execute @s ~1 ~1 ~ detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~1 ~ detect ~ ~ ~ log axis=y,variant=birch execute @s ~1 ~1 ~ detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:2,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~1 ~ detect ~ ~ ~ log axis=y,variant=jungle execute @s ~1 ~1 ~ detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:3,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~1 ~ detect ~ ~ ~ log axis=y execute @s ~1 ~1 ~ detect ~ ~-1 ~ air -1 setblock ~ ~ ~ air 0
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~1 ~ detect ~ ~ ~ log2 axis=y,variant=acacia execute @s ~1 ~1 ~ detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~1 ~ detect ~ ~ ~ log2 axis=y,variant=dark_oak execute @s ~1 ~1 ~ detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~1 ~1 ~ detect ~ ~ ~ log2 axis=y execute @s ~1 ~1 ~ detect ~ ~-1 ~ air -1 setblock ~ ~ ~ air 0

execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~1 ~1 detect ~ ~ ~ log axis=y,variant=oak execute @s ~ ~1 ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~1 ~1 detect ~ ~ ~ log axis=y,variant=spruce execute @s ~ ~1 ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~1 ~1 detect ~ ~ ~ log axis=y,variant=birch execute @s ~ ~1 ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:2,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~1 ~1 detect ~ ~ ~ log axis=y,variant=jungle execute @s ~ ~1 ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:3,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~1 ~1 detect ~ ~ ~ log axis=y execute @s ~ ~1 ~1 detect ~ ~-1 ~ air -1 setblock ~ ~ ~ air 0
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~1 ~1 detect ~ ~ ~ log2 axis=y,variant=acacia execute @s ~ ~1 ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~1 ~1 detect ~ ~ ~ log2 axis=y,variant=dark_oak execute @s ~ ~1 ~1 detect ~ ~-1 ~ air -1 summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~1 ~1 detect ~ ~ ~ log2 axis=y execute @s ~ ~1 ~1 detect ~ ~-1 ~ air -1 setblock ~ ~ ~ air 0

# Upward propagation
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~1 ~ detect ~ ~ ~ log axis=y,variant=oak summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~1 ~ detect ~ ~ ~ log axis=y,variant=spruce summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~1 ~ detect ~ ~ ~ log axis=y,variant=birch summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:2,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:22,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~1 ~ detect ~ ~ ~ log axis=y,variant=jungle summon falling_block ~ ~ ~ {DropItem:1b,TileID:17,Data:3,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:30,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~1 ~ detect ~ ~ ~ log axis=y setblock ~ ~ ~ air 0
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~1 ~ detect ~ ~ ~ log2 axis=y,variant=acacia summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:0,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~1 ~ detect ~ ~ ~ log2 axis=y,variant=dark_oak summon falling_block ~ ~ ~ {DropItem:1b,TileID:162,Data:1,Time:1s,Tags:["T4_T_f","T4_T_log"],FallHurtAmount:5.0f,FallHurtMax:26,HurtEntities:1b}
execute @e[tag=T4_T_f,score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block] ~ ~1 ~ detect ~ ~ ~ log2 axis=y setblock ~ ~ ~ air 0

scoreboard players add @s T4_T_itl 1

function Timberjack:Package/Leavesinit if @e[score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block]
scoreboard players add @e[tag=T4_T_f,type=falling_block] T4_T_ftime 1

# Loop unlimited times until fully propagated
execute @s[score_T4_T_itl=75] ~ ~ ~ function Timberjack:Package/Propagator if @e[score_T4_T_ftime_min=1,score_T4_T_ftime=1,type=falling_block]
