# (C) TesseractFour by ChocoParrot, 2017
# All rights reserved
# Potentia by ChocoParrot & Kroppeb

# Mass Functional Energy Unit (MFEU)
execute @e[type=armor_stand,tag=T4_MC1,score_T4_aec_min=9] ~ ~ ~ testforblock ~ ~ ~ dropper facing=up {Items:[{Slot:0b,id:"minecraft:diamond",Count:1b,tag:{display:{Lore:["§7Capacity: §a1000.0 §7kTx"],Name:"§fEnergy Crystal (§9Uncharged§f)"}},Damage:0s},{Slot:1b,id:"minecraft:iron_block",Count:1b,Damage:0s},{Slot:2b,id:"minecraft:obsidian",Count:1b,Damage:0s},{Slot:3b,id:"minecraft:iron_block",Count:1b,Damage:0s},{Slot:4b,id:"minecraft:comparator",Count:1b,Damage:0s},{Slot:5b,id:"minecraft:iron_block",Count:1b,Damage:0s},{Slot:6b,id:"minecraft:obsidian",Count:1b,Damage:0s},{Slot:7b,id:"minecraft:iron_block",Count:1b,Damage:0s},{Slot:8b,id:"minecraft:diamond",Count:1b,tag:{display:{Lore:["§7Capacity: §a1000.0 §7kTx"],Name:"§fEnergy Crystal (§9Uncharged§f)"}},Damage:0s}]}
execute @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] ~ ~ ~ blockdata ~ ~ ~ {CustomName:"§rMass Functional Energy Unit (MFEU)",Items:[],Lock:"§§§§§§§§"}
execute @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] ~ ~ ~ clone ~ ~ ~ ~ ~ ~ ~ ~ ~ replace force
execute @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] ~ ~ ~ playsound minecraft:block.comparator.click block @a ~ ~ ~ 1.1 0
scoreboard players set @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] T4_P_tr 10
scoreboard players set @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] T4_P_energy 0
scoreboard players set @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] T4_P_me 2999
scoreboard players set @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] T4_P_mea 3000
entitydata @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] {Tags:["T4_P_mfeu","T4_P_machine","T4_P_storage","T4_P_storagex","T4_machine","T4_MC_derivative","T4_MC1_derivative"],CustomName:"MFEU",ArmorItems:[{},{},{},{id:"minecraft:skull",Count:1b,Damage:3s,tag:{SkullOwner:{Id:"7e0dcdb3-2255-1b5a-ac90-cf89860d2980"}}}]}

# Energy Tesseract (ET)
execute @e[type=armor_stand,tag=T4_MC1,score_T4_aec_min=9] ~ ~ ~ testforblock ~ ~ ~ dropper facing=up {Items:[{Slot:0b,id:"minecraft:redstone_block",Count:1b,Damage:0s},{Slot:1b,id:"minecraft:redstone_block",Count:1b,Damage:0s},{Slot:2b,id:"minecraft:redstone_block",Count:1b,Damage:0s},{Slot:3b,id:"minecraft:redstone_block",Count:1b,Damage:0s},{Slot:4b,id:"minecraft:redstone_block",Count:1b,Damage:0s},{Slot:5b,id:"minecraft:redstone_block",Count:1b,Damage:0s},{Slot:6b,id:"minecraft:redstone_block",Count:1b,Damage:0s},{Slot:7b,id:"minecraft:redstone_block",Count:1b,Damage:0s},{Slot:8b,id:"minecraft:redstone_block",Count:1b,Damage:0s}]}
execute @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] ~ ~ ~ blockdata ~ ~ ~ {CustomName:"§rEnergy Tesseract (ET)",Items:[],Lock:"§§§§§§§§"}
execute @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] ~ ~ ~ clone ~ ~ ~ ~ ~ ~ ~ ~ ~ replace force
execute @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] ~ ~ ~ playsound minecraft:block.comparator.click block @a ~ ~ ~ 1.1 0
scoreboard players set @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] T4_P_tr 20
scoreboard players set @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] T4_P_energy 0
scoreboard players set @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] T4_P_me 7999
scoreboard players set @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] T4_P_mea 8000
entitydata @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] {Tags:["T4_P_et","T4_P_machine","T4_P_storage","T4_P_storagex","T4_machine","T4_MC_derivative","T4_MC1_derivative"],CustomName:"Energy Tesseract",ArmorItems:[{},{},{},{id:"minecraft:skull",Damage:3s,Count:1b,tag:{SkullOwner:{Id:"1868ebd4-d61f-355a-9802-de14435c7d1a",Properties:{textures:[{Signature:"K4LiTESAR8OLNlaBNQ3HRwozegeHzvZoCWFF+9ye5mPl2lAfs58dX0E538CIDvXsU5gzPY1km/mi1TKYbULIthV+l4d9R8AtsA/Yo9j/aNbegrsQjmEk3VisMp5roczLv2XLAfES0cddf89M1LMfkmTzrBXzumbu4ElbA21YaWReRaGSsB3XB1eqFntnrw9wtYMs/EcNirH+1IrHlaI0lLHrIs6HmMO8ETPiEx4EaNAaHaZdjYMZrmiMEm25ZFqa8W27dlNfBLukhcVzuvZ9jRcRy+8ssJxVlaOuD7XJbzZD9qa0S9VHyFj6ztfFdGp70mYj2dCUjejZO8Bn7/RTxXCBCQ9v4V6y1Xt0pYEvVewkFEDlYBkgMrQnbHL8C+C6LFcpkXkXzc++1Jm1hRIQMgg2btAnSSMULADl2DT4R/xRIUdv73yCkiDnhYVnVPqyYzZVkLbbOyLH8gDX2BzlpyTcib4o0GuFTGhaaVgCmTl8IvT35G06YzbFW8iBGkPDwLf/Hn6EWErS9Hdy1Tms0F9eWR3LAo8DrEnol85SWgq4VxDQu/lHYwkrwKLOErOXWfZRSs/GLb0Kn3TCDaseS0z4uvXZ/ijevD6oUqggGv1bFAOigTZu0tq4CbNt+iFxctbPY5sgDjjSFn7avVWXRPUs0kc6SQO0jBjk9RGBAF0=",Value:"eyJ0aW1lc3RhbXAiOjE1MDQ0NDg5MjU1MjQsInByb2ZpbGVJZCI6ImJmMzU3YmY0MDcyMTRiN2RiYTA0MjU3MWVjMzJjYTZmIiwicHJvZmlsZU5hbWUiOiJDb2xieUJlZWVlIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS80NTQ2ZmY5N2IzMTJmNGQ4ZGMxYWRiYWM5ZGFhN2VjMjc2OTk0MGZkODU0ZDdjMzM3ZDRlZmI4NDMxNjViZmVlIn19fQ=="}]}}}}]}

# Compact Exchange Unit (CXU)
execute @e[type=armor_stand,tag=T4_MC1,score_T4_aec_min=9] ~ ~ ~ testforblock ~ ~ ~ dropper facing=up {Items:[{Slot:0b,id:"minecraft:gold_block",Count:1b,Damage:0s},{Slot:1b,id:"minecraft:gold_block",Count:1b,Damage:0s},{Slot:2b,id:"minecraft:gold_block",Count:1b,Damage:0s},{Slot:3b,id:"minecraft:gold_block",Count:1b,Damage:0s},{Slot:4b,id:"minecraft:gold_block",Count:1b,Damage:0s},{Slot:5b,id:"minecraft:gold_block",Count:1b,Damage:0s},{Slot:6b,id:"minecraft:gold_block",Count:1b,Damage:0s},{Slot:7b,id:"minecraft:gold_block",Count:1b,Damage:0s},{Slot:8b,id:"minecraft:gold_block",Count:1b,Damage:0s}]}
execute @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] ~ ~ ~ blockdata ~ ~ ~ {CustomName:"§rCompact Exchange Unit (CXU)",Items:[],Lock:"§§§§§§§§"}
execute @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] ~ ~ ~ clone ~ ~ ~ ~ ~ ~ ~ ~ ~ replace force
execute @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] ~ ~ ~ playsound minecraft:block.comparator.click block @a ~ ~ ~ 1.1 0
scoreboard players set @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] T4_P_tr2 5
scoreboard players set @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] T4_P_energy 0
scoreboard players set @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] T4_P_me 14999
scoreboard players set @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] T4_P_mea 15000
entitydata @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] {Tags:["T4_P_cxu","T4_P_machine","T4_P_storage2","T4_P_storagex","T4_machine","T4_MC_derivative","T4_MC1_derivative"],CustomName:"Compact Exchange Unit",ArmorItems:[{},{},{},{id:"minecraft:skull",Damage:3s,Count:1b,tag:{SkullOwner:{Id:"9f930d36-14e3-45b5-9523-0a79c8b71610",Properties:{textures:[{Signature:"dzkCTbp9laYpVCjvMVQHeLvJF198cQXBQbj22xfDB2FpVMGtLWfOvch7FTF1pmauWDKbIbVizUZ4JUFzRdazPmy+hO2wTfJbfsLtW4JpT4nPULpmlUl49UcfPEMU5Gu5eK+tMRc/Cj88Osokd8eUM7zSFo8oCw/InmOLnEmqTmczs7gM4ZFeboE4n4cRhcnb8Ig230JRXQ/e35p7wXtTlRqMD9zhmPsWoIsht/NHW281aa94ORx2/CrbtWXHEU/0rQGcVI7J7kVaxVhm0wX39NZ0/eP2tJBLgosc3obvSejBqPNvxoCCcvIGXzvaWgGer12GRVrcakO/eyV+49h/67wFMs2ZpubQf1xGmsq3wbGiiauHWwS9oX5SVNZ2LG0z+VBADusXN1VpQXCTV1W0/v7t9awdEjeY8FX9HldYRfSsB2Nibr+XehcNINKxUczEQTk0+Cbm0HqxlItKBN8POlwIwrlj2IeYxDpNDZPHhGhz1Xk0JmjqJVUUq2ksDH4cnKz5xlYeIXUkPl6bUG9VSjlY/pTuyyJKTQdkSEhGfdf6wcJvCc1pVJ0fMVfhvuyv51p/2hSnnEukru7ag6vKhGoZ41Q2VezCB+fP71tXlCiXX+9NhUv9SNw31TczDYZEWK/7Kg9Mw7zl66cMABOdyWztZpQPcloe4di0umv7S6U=",Value:"eyJ0aW1lc3RhbXAiOjE1MDY5MzMxOTcwMjIsInByb2ZpbGVJZCI6ImQxY2VjOWFkMWRhODQxNzliMWU1NjA0ZjcyYmZiMjI2IiwicHJvZmlsZU5hbWUiOiJydXRnZXI0NjUiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzViZTY3ZTlmY2ZlNGJhMTFmMmM1N2QyNzc3YWY3YTVjZjU5ZjI1MzE2ZjNhNDVlZGFkN2U2OGYzNzMyY2FjMCJ9fX0="}]}}}}]}

# Mass Energy Exchange Unit (MEXU)
execute @e[type=armor_stand,tag=T4_MC1,score_T4_aec_min=9] ~ ~ ~ testforblock ~ ~ ~ dropper facing=up {Items:[{Slot:0b,id:"minecraft:iron_block",Count:1b,Damage:0s},{Slot:1b,id:"minecraft:iron_block",Count:1b,Damage:0s},{Slot:2b,id:"minecraft:iron_block",Count:1b,Damage:0s},{Slot:3b,id:"minecraft:iron_block",Count:1b,Damage:0s},{Slot:4b,id:"minecraft:iron_block",Count:1b,Damage:0s},{Slot:5b,id:"minecraft:iron_block",Count:1b,Damage:0s},{Slot:6b,id:"minecraft:iron_block",Count:1b,Damage:0s},{Slot:7b,id:"minecraft:iron_block",Count:1b,Damage:0s},{Slot:8b,id:"minecraft:iron_block",Count:1b,Damage:0s}]}
execute @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] ~ ~ ~ blockdata ~ ~ ~ {CustomName:"§rMass Energy Exchange Unit (MEXU)",Items:[],Lock:"§§§§§§§§"}
execute @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] ~ ~ ~ clone ~ ~ ~ ~ ~ ~ ~ ~ ~ replace force
execute @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] ~ ~ ~ playsound minecraft:block.comparator.click block @a ~ ~ ~ 1.1 0
scoreboard players set @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] T4_P_tr2 15
scoreboard players set @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] T4_P_energy 0
scoreboard players set @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] T4_P_me 39999
scoreboard players set @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] T4_P_mea 40000
entitydata @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] {Tags:["T4_P_mexu","T4_P_machine","T4_P_storage2","T4_P_storagex","T4_machine","T4_MC_derivative","T4_MC1_derivative"],CustomName:"Mass Energy Exchange Unit (MEXU)",ArmorItems:[{},{},{},{id:"minecraft:skull",Damage:3s,Count:1b,tag:{SkullOwner:{Id:"a248746b-a5b9-4965-809c-5f553ab236be",Properties:{textures:[{Signature:"dgpn5litkMWcM0f1q6ye4ZCwbQ0kDGjSL1hjZngtwm/eG239oImql1CIRcHmAhnizltVY9QvW9VIu+aXe1pEMdJ237PZnzgTHOQViwmtnPrfuRHK4GffgFkiW6nsWLr0WS9Ho8a77KdV9rpJFbM7VlZQkSI42aqk2FnMDdXm5Dw/5SA5uWZ9HShOQxzFNmFNuksnqL1fhzi+rykQrAl3RHVLll436Yn1/N250sufmHaN1yO/B5u7lFxN6orDuEFLkNtkbJYHsJ4P2K50txDo3LGRh5Nb/JJyGGk1em2dKdGdDNEj8L5LiMshhWQhjgdNDZ4qecCY+3cLejAkr2l9S6AAIyvxdUIBfrq5FQNYo1mzyn+N8X9Ech3FxLOFUjD9abeKPS64irwRGmF71vw4ZfCThzdPzVeB/pJY2izUmMW37FDmll8J7x/r/uSMIKjHTvaMddkp+0TTGKRtQxA/60MBxtVilZ0G5xxi5q9uhdtkUm8diFGPBxXP5m2xbNJcRkwitgYXio85l7cDJpJWErBZPMf6qEpG9mmT5hxHz2sOj+hsETYVw6Ou9tVnLUkUD+MOh6tRcWSVfalvXCtAyujN0vfVgd6CR7JO+EFtIAedVz3o9w4SYD4g1CcPjpVZeGuhsNELgOe1G2DNl259eFEq3VaBjQ5BfoztBNxz0bI=",Value:"eyJ0aW1lc3RhbXAiOjE1MDY5OTYwMTUyMTYsInByb2ZpbGVJZCI6ImJiMDgwOTFhOTJlZDQzYWQ5NGYxZWRmZDc0NmIwYTJjIiwicHJvZmlsZU5hbWUiOiJJcDRuZHgiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzlhN2RiNmFhZWNmYjA3MTM2ODY1OGQwYTRiNDE1ZjQ3MWQ4MmY5MjQ3MTE2ZDNlNjZhODllMjZkNDI5YTUifX19"}]}}}}]}

# Lapotronic Tesseract (LT)
execute @e[type=armor_stand,tag=T4_MC1,score_T4_aec_min=9] ~ ~ ~ testforblock ~ ~ ~ dropper facing=up {Items:[{Slot:0b,id:"minecraft:beacon",Count:1b,Damage:0s},{Slot:1b,id:"minecraft:beacon",Count:1b,Damage:0s},{Slot:2b,id:"minecraft:beacon",Count:1b,Damage:0s},{Slot:3b,id:"minecraft:beacon",Count:1b,Damage:0s},{Slot:4b,id:"minecraft:beacon",Count:1b,Damage:0s},{Slot:5b,id:"minecraft:beacon",Count:1b,Damage:0s},{Slot:6b,id:"minecraft:beacon",Count:1b,Damage:0s},{Slot:7b,id:"minecraft:beacon",Count:1b,Damage:0s},{Slot:8b,id:"minecraft:beacon",Count:1b,Damage:0s}]}
execute @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] ~ ~ ~ blockdata ~ ~ ~ {CustomName:"§rLapotronic Tesseract (LT)",Items:[],Lock:"§§§§§§§§"}
execute @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] ~ ~ ~ clone ~ ~ ~ ~ ~ ~ ~ ~ ~ replace force
execute @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] ~ ~ ~ playsound minecraft:block.comparator.click block @a ~ ~ ~ 1.1 0
scoreboard players set @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] T4_P_tr2 80
scoreboard players set @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] T4_P_energy 0
scoreboard players set @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] T4_P_me 499999
scoreboard players set @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] T4_P_mea 500000
entitydata @e[type=armor_stand,tag=T4_MC1,score_T4_MC_recipes_min=1,score_T4_aec_min=9] {Tags:["T4_P_lt","T4_P_machine","T4_P_storage2","T4_P_storagex","T4_machine","T4_MC_derivative","T4_MC1_derivative"],CustomName:"Lapotronic Tesseract (LT)",ArmorItems:[{},{},{},{id:"minecraft:skull",Damage:3s,Count:1b,tag:{SkullOwner:{Id:"05817146-ba70-4d94-a736-95ba5d18f502",Properties:{textures:[{Signature:"cwh5k1SeqKmNaLq87FOtKcLZlpOmsFE8E/ePK1+9Q4o93R7f1mP+0ufWSCERhu546jIKdXMKQKi2LgJ3HzT7dUVXUInzNzIgz9tG4FVsfG5iLPUE6FgwKzjzuAXOlmUKZEqWpBMjtCX31S4TePgpUNaWd5oYDmInjcqToMDlmtgCjeX9XA8cFewpi//z2nkIqoPq5UQ+HLrf1PTTnmtnHf9+xyhkcNaOjN93Q/3ul6U4tfPqFkc4v8eDnX492bbqjJLPUuzYA7rA+7sqoOFbQI5y4IbnG9G4rjbrR2IBS0vm5Wy+sLj+s4WSiMinOdrt2pwlQ1q9K7OLF2IxI7npRYjhNlxUUmxHCgrqCul+cGVVknglw5QMyUlckrEnf/ajRCM2nXfQXQAj8vofpk/IgmELtv3F/DuSmtcU/y2NnZSGycXZKv7SswFdnfh/Mu6pmBWwPZeqn760XLBrHU6jtDqhtyB02CzXDTM2/3DrhtCM64DPVL6eCrWbAEr3PUH/AUbTS4Xz1M485Kze0Fwy+2KKnb1bl2OVTqMg0gQlNNzNWAvPP4H89gD8EB1JKOxLB11+fXlELXVxhsB9skQDVz68LK66TX2EEyP/rrH6qhhyvDU09dP8RATg4KKfTReXRo1fDB3P7ztLGl4EQCAQgqkCAUjD/HOLPQoWQEcxSSo=",Value:"eyJ0aW1lc3RhbXAiOjE1MDc0MzEyMjc2NzIsInByb2ZpbGVJZCI6IjcwOTU2NDU0NTJkOTRiYTI5YzcwZDFmYTY3YjhkYTQyIiwicHJvZmlsZU5hbWUiOiJIaWRkdXMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzc3ZDg5OTIzMTJjMGRlOTFhMmQ1OWEzM2EyMTc0M2RjNjI0NzkzMWY2ZGE2ZTI3MWEzNzZjY2RhM2M4YmI1N2IifX19"}]}}}}]}
